import { pilotQuestion, type PilotQuestionSeed } from "./pilot-factory";

const q = (seed: Omit<PilotQuestionSeed, "grade">) => pilotQuestion({ grade: 6, ...seed });

export const grade6Questions = [
  q({ id: "g6-diagnostic-place-01", skill: "comprehension", indicator: "能理解地點與去向問答", microSkill: "place-and-destination", difficulty: 1, purpose: "diagnostic", prompt: "A: Where are you going? B: I'm going to the ___. I want to borrow a book.", options: ["library", "hospital", "park"], answerIndex: 0, explanation: "borrow a book 是去 library 的線索。", hints: ["哪一個地方可以借書？"], variantGroup: "g6-place-library" }),
  q({ id: "g6-diagnostic-progressive-01", skill: "grammar", indicator: "能理解現在進行式", microSkill: "present-progressive", difficulty: 1, purpose: "diagnostic", modality: "image", imageScene: "girl-reading-at-desk", imageAlt: "一位女孩在書桌旁進行活動的情境圖，請依題幹選句子", prompt: "What is she doing?", options: ["She is reading.", "She reads every day.", "She can read."], answerIndex: 0, explanation: "正在發生的動作使用 is reading。", hints: ["問句有 is doing，回答也要用 is＋動詞 ing。"], variantGroup: "g6-progressive-reading" }),
  q({ id: "g6-diagnostic-clothing-have-01", skill: "grammar", indicator: "能理解衣物與 have 句型", microSkill: "clothing-and-have", difficulty: 1, purpose: "diagnostic", prompt: "I ___ a blue jacket.", options: ["have", "has", "am"], answerIndex: 0, explanation: "主詞 I 搭配 have。", hints: ["I 和 you 都使用 have。"], variantGroup: "g6-have-jacket" }),
  q({ id: "g6-diagnostic-occupation-family-01", skill: "vocabulary", indicator: "能理解職業與家庭資訊", microSkill: "occupation-and-family", difficulty: 1, purpose: "diagnostic", prompt: "My mother works in a hospital and helps sick people. She is a ___.", options: ["doctor", "farmer", "driver"], answerIndex: 0, explanation: "在醫院幫助病人的職業是 doctor。", hints: ["hospital 是關鍵地點。"], variantGroup: "g6-job-doctor" }),
  q({ id: "g6-diagnostic-integrated-01", skill: "comprehension", indicator: "能理解整合式短對話", microSkill: "integrated-dialogue-text", difficulty: 2, purpose: "diagnostic", prompt: "A: Where is Leo? B: He is in the kitchen. He is making lunch. What is Leo doing?", options: ["He is making lunch.", "He is going to school.", "He is washing his jacket."], answerIndex: 0, explanation: "對話直接說 He is making lunch。", hints: ["答案藏在 B 的第二句。"], variantGroup: "g6-dialogue-leo-lunch" }),
  q({ id: "g6-progressive-practice-01", skill: "grammar", indicator: "能使用 is＋動詞 ing 描述動作", microSkill: "present-progressive", difficulty: 1, purpose: "practice", modality: "image", imageScene: "girl-reading-on-sofa", imageAlt: "一位女孩在室內進行安靜活動的情境圖，請選句子", prompt: "What is the girl doing?", options: ["She is reading.", "She reading.", "She reads now."], answerIndex: 0, explanation: "現在進行式需要 She is reading。", hints: ["別忘了主詞後面的 is。"], variantGroup: "g6-progressive-girl-reading" }),
  q({ id: "g6-progressive-practice-02", skill: "grammar", indicator: "能使用 are＋動詞 ing 描述複數動作", microSkill: "present-progressive", difficulty: 1, purpose: "practice", modality: "image", imageScene: "children-playing-soccer", imageAlt: "幾位孩子在戶外進行球類活動的情境圖，請選句子", prompt: "What are the children doing?", options: ["They are playing soccer.", "They is playing soccer.", "They play soccer now."], answerIndex: 0, explanation: "複數主詞 They 搭配 are playing。", hints: ["They 後面使用 are。"], variantGroup: "g6-progressive-soccer" }),
  q({ id: "g6-progressive-practice-03", skill: "classroom_english", indicator: "能回答 What are you doing?", microSkill: "present-progressive", difficulty: 1, purpose: "practice", prompt: "What are you doing?", options: ["I am doing my homework.", "I do my homework yesterday.", "I can homework."], answerIndex: 0, explanation: "正在做功課使用 I am doing my homework。", hints: ["問句是 doing，回答要有 am＋doing。"], variantGroup: "g6-progressive-homework" }),
  q({ id: "g6-progressive-practice-04", skill: "grammar", indicator: "能理解現在進行式否定句", microSkill: "present-progressive", difficulty: 2, purpose: "practice", prompt: "Ben is studying now. Which sentence is true?", options: ["He isn't sleeping.", "He aren't studying.", "He doesn't studying."], answerIndex: 0, explanation: "Ben 正在讀書，因此 He isn't sleeping 是正確描述。", hints: ["is not 的縮寫是 isn't。"], variantGroup: "g6-progressive-not-sleeping" }),
  q({ id: "g6-progressive-practice-05", skill: "grammar", indicator: "能辨認正確的現在進行式", microSkill: "present-progressive", difficulty: 1, purpose: "practice", prompt: "Choose the correct sentence for an action happening now.", options: ["The dog is running.", "The dog running.", "The dog are run."], answerIndex: 0, explanation: "單數主詞 The dog 使用 is running。", hints: ["找出 is＋動詞 ing 的選項。"], variantGroup: "g6-progressive-dog-running" }),
  q({ id: "g6-progressive-boss-01", skill: "comprehension", indicator: "能整合對話與現在進行式", microSkill: "present-progressive", difficulty: 2, purpose: "boss", prompt: "A: Where are Mom and Dad? B: They are in the kitchen. Mom is cooking, and Dad is washing dishes. Which is true?", options: ["Mom is cooking and Dad is washing dishes.", "Mom and Dad are sleeping.", "Dad is cooking and Mom is reading."], answerIndex: 0, explanation: "對話分別說明 Mom is cooking 與 Dad is washing dishes。", hints: ["把 Mom 和 Dad 的動作分開核對。"], variantGroup: "g6-progressive-boss-kitchen" }),
  q({ id: "g6-progressive-rescue-01", skill: "grammar", indicator: "能辨識動詞 ing 形式", microSkill: "present-progressive", difficulty: 1, purpose: "rescue", prompt: "read → ____", options: ["reading", "reades", "readed"], answerIndex: 0, explanation: "read 加 ing 成為 reading。", hints: ["把 ing 直接接在 read 後面。"], variantGroup: "g6-progressive-rescue-reading" }),
  q({ id: "g6-progressive-rescue-02", skill: "grammar", indicator: "能完成 is＋動詞 ing 句型", microSkill: "present-progressive", difficulty: 1, purpose: "rescue", prompt: "She ___ singing now.", options: ["is", "are", "do"], answerIndex: 0, explanation: "She 是單數主詞，搭配 is singing。", hints: ["She、he、it 都搭配 is。"], variantGroup: "g6-progressive-rescue-singing" }),
  q({ id: "g6-progressive-review-01", skill: "comprehension", indicator: "能跨日理解現在進行式問答", microSkill: "present-progressive", difficulty: 2, purpose: "review", prompt: "Dad is in the kitchen. He has a pan in his hand. What is he doing?", options: ["He is cooking.", "He is driving.", "He is swimming."], answerIndex: 0, explanation: "kitchen 和 pan 都是正在煮飯的線索。", hints: ["先找地點與物品兩個線索。"], variantGroup: "g6-progressive-review-cooking" }),
  q({ id: "g6-progressive-review-02", skill: "classroom_english", indicator: "能回答現在進行式 Yes／No 問句", microSkill: "present-progressive", difficulty: 2, purpose: "review", modality: "image", imageScene: "two-children-dancing", imageAlt: "兩位孩子進行肢體活動的情境圖，請依題幹回答", prompt: "Are they dancing?", options: ["Yes, they are.", "Yes, they do.", "No, they aren't."], answerIndex: 0, explanation: "圖中兩人正在跳舞，Are they ...? 回答 Yes, they are.", hints: ["Are 問、are 答。"], variantGroup: "g6-progressive-review-dancing" }),
];
