import { pilotQuestion, type PilotQuestionSeed } from "./pilot-factory";

const q = (seed: Omit<PilotQuestionSeed, "grade">) => pilotQuestion({ grade: 4, ...seed });

export const grade4Questions = [
  q({ id: "g4-diagnostic-image-sentence-01", skill: "comprehension", indicator: "能進行圖句配對", microSkill: "image-sentence-match", difficulty: 1, purpose: "diagnostic", modality: "image", imageScene: "child-reading-book", imageAlt: "一位孩子進行日常活動的情境圖，請依題幹選句子", prompt: "Which sentence matches the picture?", options: ["He is reading.", "He is running.", "He is sleeping."], answerIndex: 0, explanation: "圖中的孩子正在閱讀，所以選 He is reading.", hints: ["先看孩子手上拿著什麼。"], variantGroup: "g4-image-reading" }),
  q({ id: "g4-diagnostic-affirmative-negative-01", skill: "grammar", indicator: "能理解基礎肯定與否定句", microSkill: "affirmative-negative", difficulty: 1, purpose: "diagnostic", prompt: "Amy is not tired. Choose the sentence with the same meaning.", options: ["Amy isn't tired.", "Amy is tired.", "Amy isn't happy."], answerIndex: 0, explanation: "is not 可以縮寫成 isn't。", hints: ["找出 is not 的縮寫。"], variantGroup: "g4-negative-tired" }),
  q({ id: "g4-diagnostic-this-that-01", skill: "grammar", indicator: "能依距離使用 this 與 that", microSkill: "this-that-questions", difficulty: 1, purpose: "diagnostic", prompt: "The pencil is near you. ___ is a pencil.", options: ["This", "That", "Those"], answerIndex: 0, explanation: "靠近自己的單數物品使用 This。", hints: ["near 表示東西就在近處。"], variantGroup: "g4-this-pencil" }),
  q({ id: "g4-diagnostic-yes-no-01", skill: "classroom_english", indicator: "能回應基礎 Yes／No 問句", microSkill: "yes-no-questions", difficulty: 1, purpose: "diagnostic", prompt: "Is this your book? Choose a correct short answer.", options: ["Yes, it is.", "Yes, I is.", "Yes, this do."], answerIndex: 0, explanation: "Is this ...? 的肯定簡答是 Yes, it is.", hints: ["問句用 Is，回答也要保留 is。"], variantGroup: "g4-yes-no-book" }),
  q({ id: "g4-diagnostic-cvc-01", skill: "phonics", indicator: "能解碼基礎 CVC 字詞", microSkill: "cvc-decoding", difficulty: 1, purpose: "diagnostic", prompt: "Which word is /d/ /ɒ/ /g/?", options: ["dog", "dig", "dug"], answerIndex: 0, explanation: "/d/＋/ɒ/＋/g/ 合起來是 dog。", hints: ["注意中間是短 o 音。"], variantGroup: "g4-cvc-dog" }),
  q({ id: "g4-yes-no-practice-01", skill: "classroom_english", indicator: "能回答 Is this ...?", microSkill: "yes-no-questions", difficulty: 1, purpose: "practice", prompt: "Is this a pen?", options: ["Yes, it is.", "Yes, I am.", "Yes, they are."], answerIndex: 0, explanation: "this 代表單數物品，使用 it 回答。", hints: ["問的是物品，不是人。"], variantGroup: "g4-yn-pen" }),
  q({ id: "g4-yes-no-practice-02", skill: "classroom_english", indicator: "能回答 Are you ...?", microSkill: "yes-no-questions", difficulty: 1, purpose: "practice", prompt: "Are you happy?", options: ["Yes, I am.", "Yes, it is.", "Yes, you are."], answerIndex: 0, explanation: "Are you ...? 由自己回答時使用 Yes, I am.", hints: ["把問句中的 you 換成 I。"], variantGroup: "g4-yn-happy" }),
  q({ id: "g4-yes-no-practice-03", skill: "classroom_english", indicator: "能依資訊回答 Is he ...?", microSkill: "yes-no-questions", difficulty: 1, purpose: "practice", prompt: "Tom is a teacher. Is Tom a student?", options: ["No, he isn't.", "Yes, he is.", "No, it isn't."], answerIndex: 0, explanation: "Tom 是老師，不是學生，所以回答 No, he isn't.", hints: ["先找第一句說 Tom 是什麼身分。"], variantGroup: "g4-yn-tom" }),
  q({ id: "g4-yes-no-practice-04", skill: "classroom_english", indicator: "能回答 Can she ...?", microSkill: "yes-no-questions", difficulty: 1, purpose: "practice", prompt: "Mia can swim. Can she swim?", options: ["Yes, she can.", "Yes, she is.", "No, she can't."], answerIndex: 0, explanation: "第一句說 Mia 會游泳，因此回答 Yes, she can.", hints: ["Can 問句要用 can 回答。"], variantGroup: "g4-yn-mia-swim" }),
  q({ id: "g4-yes-no-practice-05", skill: "classroom_english", indicator: "能回答 Are these ...?", microSkill: "yes-no-questions", difficulty: 2, purpose: "practice", modality: "image", imageScene: "three-red-apples", imageAlt: "三個相同物品的情境圖，請依題幹回答", prompt: "Are these apples?", options: ["Yes, they are.", "Yes, it is.", "No, they aren't."], answerIndex: 0, explanation: "these 是複數，肯定回答使用 they are。", hints: ["圖中不只一個，所以要用 they。"], variantGroup: "g4-yn-apples" }),
  q({ id: "g4-yes-no-boss-01", skill: "comprehension", indicator: "能在對話中選出適當 Yes／No 回應", microSkill: "yes-no-questions", difficulty: 2, purpose: "boss", prompt: "A: Is that your ruler? B: ____. My ruler is blue, not red.", options: ["No, it isn't.", "Yes, that is.", "No, I am not."], answerIndex: 0, explanation: "後句說自己的尺不是紅色，所以先回答 No, it isn't.", hints: ["not red 是拒絕的線索。"], variantGroup: "g4-yn-boss-ruler" }),
  q({ id: "g4-yes-no-rescue-01", skill: "classroom_english", indicator: "能以固定句型回答 Is it ...?", microSkill: "yes-no-questions", difficulty: 1, purpose: "rescue", modality: "image", imageScene: "single-cat", imageAlt: "一隻動物的情境圖，請依題幹回答", prompt: "Is it a cat?", options: ["Yes, it is.", "Yes, I am.", "No, they aren't."], answerIndex: 0, explanation: "單數動物用 it，肯定回答是 Yes, it is.", hints: ["照著 Is it 的兩個字回答。"], variantGroup: "g4-yn-rescue-cat" }),
  q({ id: "g4-yes-no-rescue-02", skill: "classroom_english", indicator: "能以固定句型回答 Are you ...?", microSkill: "yes-no-questions", difficulty: 1, purpose: "rescue", prompt: "Are you ready?", options: ["Yes, I am.", "Yes, it is.", "Yes, I do."], answerIndex: 0, explanation: "Are you ...? 的肯定簡答是 Yes, I am.", hints: ["把 Are you 變成 I am。"], variantGroup: "g4-yn-rescue-ready" }),
  q({ id: "g4-yes-no-review-01", skill: "classroom_english", indicator: "能跨情境回答 Is she ...?", microSkill: "yes-no-questions", difficulty: 1, purpose: "review", prompt: "Lily is tall. Is she tall?", options: ["Yes, she is.", "Yes, she does.", "No, she isn't."], answerIndex: 0, explanation: "第一句確認 Lily 很高，因此回答 Yes, she is.", hints: ["Is she 問句用 she is 回答。"], variantGroup: "g4-yn-review-lily" }),
  q({ id: "g4-yes-no-review-02", skill: "comprehension", indicator: "能依圖文資訊回答複數問句", microSkill: "yes-no-questions", difficulty: 2, purpose: "review", modality: "image", imageScene: "two-cardboard-boxes", imageAlt: "兩個相同容器的情境圖，請依題幹回答", prompt: "Are these books?", options: ["No, they aren't.", "Yes, they are.", "No, it isn't."], answerIndex: 0, explanation: "圖中是 boxes，不是 books，所以回答 No, they aren't.", hints: ["these 是複數，先排除 it。"], variantGroup: "g4-yn-review-boxes" }),
];
