import { pilotQuestion, type PilotQuestionSeed } from "./pilot-factory";

const q = (seed: Omit<PilotQuestionSeed, "grade">) => pilotQuestion({ grade: 5, ...seed });

export const grade5Questions = [
  q({ id: "g5-diagnostic-weather-01", skill: "comprehension", indicator: "能聽懂基礎天氣敘述", microSkill: "weather-listening", difficulty: 1, purpose: "diagnostic", modality: "audio", audioTranscript: "It is rainy today.", prompt: "Listen. How is the weather?", options: ["It is rainy.", "It is sunny.", "It is windy."], answerIndex: 0, explanation: "音檔說 It is rainy today，所以天氣是 rainy。", hints: ["注意 rainy、sunny、windy 的第一個聲音。"], variantGroup: "g5-weather-rainy" }),
  q({ id: "g5-diagnostic-image-sentence-01", skill: "comprehension", indicator: "能理解圖像中的簡單句意", microSkill: "image-sentence-meaning", difficulty: 1, purpose: "diagnostic", modality: "image", imageScene: "child-riding-bicycle", imageAlt: "一位孩子進行戶外活動的情境圖，請選句子", prompt: "Which sentence matches the picture?", options: ["He is riding a bike.", "He is flying a kite.", "He is reading a book."], answerIndex: 0, explanation: "圖中的孩子正在騎腳踏車。", hints: ["看孩子坐在什麼交通工具上。"], variantGroup: "g5-image-bike" }),
  q({ id: "g5-diagnostic-adjective-01", skill: "vocabulary", indicator: "能理解常用形容詞", microSkill: "adjectives", difficulty: 1, purpose: "diagnostic", prompt: "A giraffe has a long neck. It is very ___.", options: ["tall", "short", "small"], answerIndex: 0, explanation: "長頸鹿很高，使用 tall。", hints: ["比較 tall 和 short 的意思。"], variantGroup: "g5-adjective-tall" }),
  q({ id: "g5-diagnostic-age-can-01", skill: "grammar", indicator: "能理解年齡與 can 句型", microSkill: "age-and-can", difficulty: 1, purpose: "diagnostic", prompt: "How old are you?", options: ["I'm eleven.", "I can swim.", "I'm fine."], answerIndex: 0, explanation: "How old 詢問年齡，回答 I'm eleven。", hints: ["找出包含數字年齡的回答。"], variantGroup: "g5-age-eleven" }),
  q({ id: "g5-diagnostic-dialogue-01", skill: "comprehension", indicator: "能理解簡短生活對話", microSkill: "short-dialogue", difficulty: 1, purpose: "diagnostic", prompt: "A: Can you dance? B: Yes, I ___.", options: ["can", "am", "do"], answerIndex: 0, explanation: "Can 問句用 can 回答。", hints: ["把問句的第一個字放回回答。"], variantGroup: "g5-dialogue-can-dance" }),
  q({ id: "g5-age-can-practice-01", skill: "grammar", indicator: "能詢問與回答他人年齡", microSkill: "age-and-can", difficulty: 1, purpose: "practice", prompt: "Leo is ten years old. How old is Leo?", options: ["He is ten.", "He can count.", "He is fine."], answerIndex: 0, explanation: "題目已說 Leo is ten years old。", hints: ["How old 問的是數字年齡。"], variantGroup: "g5-age-leo-ten" }),
  q({ id: "g5-age-can-practice-02", skill: "grammar", indicator: "能依資訊回答 Can she ...?", microSkill: "age-and-can", difficulty: 1, purpose: "practice", prompt: "Amy can draw a cat. Can she draw?", options: ["Yes, she can.", "Yes, she is.", "No, she can't."], answerIndex: 0, explanation: "第一句說 Amy can draw，所以肯定回答。", hints: ["Can she 問句要用 she can 回答。"], variantGroup: "g5-can-amy-draw" }),
  q({ id: "g5-age-can-practice-03", skill: "grammar", indicator: "能依否定資訊回答 can 問句", microSkill: "age-and-can", difficulty: 1, purpose: "practice", prompt: "Mia cannot swim. Can Mia swim?", options: ["No, she can't.", "Yes, she can.", "No, she isn't."], answerIndex: 0, explanation: "cannot 表示不會，所以回答 No, she can't.", hints: ["cannot 和 can't 意思相同。"], variantGroup: "g5-can-mia-swim" }),
  q({ id: "g5-age-can-practice-04", skill: "grammar", indicator: "能理解複數主詞的年齡回答", microSkill: "age-and-can", difficulty: 2, purpose: "practice", prompt: "The twins are twelve years old. How old are they?", options: ["They are twelve.", "They can jump.", "They are twins."], answerIndex: 0, explanation: "they 指雙胞胎，年齡是 twelve。", hints: ["找出同時有 they 和數字的選項。"], variantGroup: "g5-age-twins-twelve" }),
  q({ id: "g5-age-can-practice-05", skill: "classroom_english", indicator: "能以第一人稱回答 can 問句", microSkill: "age-and-can", difficulty: 1, purpose: "practice", prompt: "Can you play basketball? Choose a positive answer.", options: ["Yes, I can.", "Yes, you can.", "Yes, I am."], answerIndex: 0, explanation: "自己回答 Can you ...? 時使用 Yes, I can.", hints: ["you 在回答中要換成 I。"], variantGroup: "g5-can-basketball" }),
  q({ id: "g5-age-can-boss-01", skill: "comprehension", indicator: "能整合年齡與能力資訊", microSkill: "age-and-can", difficulty: 2, purpose: "boss", prompt: "Emma is eleven. She can sing, but she cannot dance. Which is true?", options: ["Emma is eleven and can sing.", "Emma is twelve and can dance.", "Emma is eleven and can dance."], answerIndex: 0, explanation: "短文同時說 Emma 十一歲而且會唱歌。", hints: ["分別核對年齡和 can 後面的動作。"], variantGroup: "g5-age-can-boss-emma" }),
  q({ id: "g5-age-can-rescue-01", skill: "grammar", indicator: "能以固定句型回答年齡", microSkill: "age-and-can", difficulty: 1, purpose: "rescue", prompt: "How old is Ben? Ben is nine. Choose the answer.", options: ["He is nine.", "He can run.", "He is Ben."], answerIndex: 0, explanation: "How old is Ben? 可回答 He is nine.", hints: ["直接把 Ben 換成 He。"], variantGroup: "g5-age-rescue-ben" }),
  q({ id: "g5-age-can-rescue-02", skill: "grammar", indicator: "能以固定句型回答能力", microSkill: "age-and-can", difficulty: 1, purpose: "rescue", prompt: "Can Lisa cook? Lisa can cook.", options: ["Yes, she can.", "Yes, she is.", "No, she can't."], answerIndex: 0, explanation: "Lisa can cook，所以回答 Yes, she can.", hints: ["照著 can 問、can 答。"], variantGroup: "g5-can-rescue-lisa" }),
  q({ id: "g5-age-can-review-01", skill: "comprehension", indicator: "能跨日整合年齡與能力問答", microSkill: "age-and-can", difficulty: 2, purpose: "review", prompt: "Kai is ten and he can skate. Which question can be answered with 'Yes, he can'?", options: ["Can Kai skate?", "Is Kai ten?", "How old is Kai?"], answerIndex: 0, explanation: "Yes, he can 對應 Can Kai skate?", hints: ["看回答中的 can，找同樣以 Can 開頭的問句。"], variantGroup: "g5-can-review-kai" }),
  q({ id: "g5-age-can-review-02", skill: "comprehension", indicator: "能在對話中選擇年齡回應", microSkill: "age-and-can", difficulty: 2, purpose: "review", prompt: "A: How old is your sister? B: ____", options: ["She is eight.", "She can sing.", "She is my sister."], answerIndex: 0, explanation: "How old 詢問年齡，所以回答 She is eight。", hints: ["找出帶有數字的選項。"], variantGroup: "g5-age-review-sister" }),
];
