import { pilotQuestion, type PilotQuestionSeed } from "../pilot/pilot-factory";

const q = (seed: Omit<PilotQuestionSeed, "grade">) => pilotQuestion({ grade: 3, ...seed });

export const grade3ReviewCandidates = [
  q({
    id: "g3-review-uppercase-lowercase-01",
    skill: "letters",
    indicator: "能辨識英文字母大小寫的對應關係",
    microSkill: "uppercase-lowercase",
    difficulty: 1,
    purpose: "practice",
    prompt: "Which lowercase letter matches M?",
    options: ["m", "n", "w"],
    answerIndex: 0,
    explanation: "大寫 M 對應的小寫字母是 m。",
    hints: ["先比較字母的主要線條。"],
    variantGroup: "g3-case-m",
  }),
  q({
    id: "g3-review-uppercase-lowercase-02",
    skill: "letters",
    indicator: "能辨識英文字母大小寫的對應關係",
    microSkill: "uppercase-lowercase",
    difficulty: 1,
    purpose: "practice",
    prompt: "Which capital letter matches r?",
    options: ["R", "P", "K"],
    answerIndex: 0,
    explanation: "小寫 r 對應的大寫字母是 R。",
    hints: ["先說出 r 的字母名稱。"],
    variantGroup: "g3-case-r",
  }),
  q({
    id: "g3-review-uppercase-lowercase-03",
    skill: "letters",
    indicator: "能辨識同一字母的大小寫形式",
    microSkill: "uppercase-lowercase",
    difficulty: 1,
    purpose: "rescue",
    prompt: "Which pair is the same letter?",
    options: ["Q q", "Q p", "G q"],
    answerIndex: 0,
    explanation: "Q 和 q 是同一個字母的大小寫形式。",
    hints: ["先逐組念出兩個字母的名稱。"],
    variantGroup: "g3-case-q",
  }),
  q({
    id: "g3-review-uppercase-lowercase-04",
    skill: "letters",
    indicator: "能辨識容易混淆的英文字母大小寫",
    microSkill: "uppercase-lowercase",
    difficulty: 1,
    purpose: "practice",
    prompt: "Find the lowercase form of D.",
    options: ["d", "b", "p"],
    answerIndex: 0,
    explanation: "大寫 D 的小寫形式是 d。",
    hints: ["注意直線在圓弧的左邊。"],
    variantGroup: "g3-case-d",
  }),
  q({
    id: "g3-review-uppercase-lowercase-05",
    skill: "letters",
    indicator: "能將大寫字母與小寫字母配對",
    microSkill: "uppercase-lowercase",
    difficulty: 1,
    purpose: "review",
    prompt: "The card shows P. Which card belongs with it?",
    options: ["p", "q", "b"],
    answerIndex: 0,
    explanation: "P 和 p 是正確的大小寫配對。",
    hints: ["念出 P，再找名稱相同的小寫字母。"],
    variantGroup: "g3-case-p",
  }),
  q({
    id: "g3-review-uppercase-lowercase-06",
    skill: "letters",
    indicator: "能檢查多組字母的大小寫配對",
    microSkill: "uppercase-lowercase",
    difficulty: 2,
    purpose: "practice",
    prompt: "Which row has three correct capital-lowercase pairs?",
    options: ["A a, B b, T t", "A a, B d, T f", "A e, B b, T t"],
    answerIndex: 0,
    explanation: "A-a、B-b、T-t 三組的字母名稱都相同。",
    hints: ["一次檢查一組，不要只看第一組。"],
    variantGroup: "g3-case-three-pairs",
  }),
  q({
    id: "g3-review-uppercase-lowercase-07",
    skill: "letters",
    indicator: "能在字母序列中辨識大小寫對應",
    microSkill: "uppercase-lowercase",
    difficulty: 2,
    purpose: "review",
    prompt: "Complete the pattern: H h, J j, K __.",
    options: ["k", "h", "j"],
    answerIndex: 0,
    explanation: "每一組都是先大寫再小寫，所以 K 後面要接 k。",
    hints: ["觀察每一組前後字母的名稱是否相同。"],
    variantGroup: "g3-case-pattern-k",
  }),
  q({
    id: "g3-review-uppercase-lowercase-08",
    skill: "letters",
    indicator: "能同時比對多組不相鄰字母的大小寫",
    microSkill: "uppercase-lowercase",
    difficulty: 3,
    purpose: "boss",
    prompt: "Which set correctly pairs all three letters: S, W, Y?",
    options: ["s w y", "s v y", "s w u"],
    answerIndex: 0,
    explanation: "S-s、W-w、Y-y 三組字母名稱都相同，其餘選項各換掉了一個字母。",
    hints: ["三組都要逐一核對，不能只看第一組就作答。"],
    variantGroup: "g3-case-boss-swy",
  }),

  q({
    id: "g3-review-letter-listening-01",
    skill: "letters",
    indicator: "能聽辨單一英文字母名稱",
    microSkill: "letter-listening",
    difficulty: 1,
    purpose: "practice",
    modality: "audio",
    audioTranscript: "E",
    prompt: "Listen. Which capital letter do you hear?",
    options: ["E", "A", "I"],
    answerIndex: 0,
    explanation: "音檔念的是字母 E。",
    hints: ["注意 E 的字母名稱以長母音 /iː/ 開始。"],
    variantGroup: "g3-listen-e",
  }),
  q({
    id: "g3-review-letter-listening-02",
    skill: "letters",
    indicator: "能聽辨字母名稱並選出小寫形式",
    microSkill: "letter-listening",
    difficulty: 1,
    purpose: "practice",
    modality: "audio",
    audioTranscript: "M",
    prompt: "Listen and choose the lowercase letter.",
    options: ["m", "n", "w"],
    answerIndex: 0,
    explanation: "音檔念 M，所以要選小寫 m。",
    hints: ["先聽出字母名稱，再找它的小寫形式。"],
    variantGroup: "g3-listen-m",
  }),
  q({
    id: "g3-review-letter-listening-03",
    skill: "letters",
    indicator: "能分辨發音相近的英文字母名稱",
    microSkill: "letter-listening",
    difficulty: 1,
    purpose: "rescue",
    modality: "audio",
    audioTranscript: "V",
    prompt: "The teacher says one letter. Which is it?",
    options: ["V", "B", "P"],
    answerIndex: 0,
    explanation: "音檔念的是 V，不是 B 或 P。",
    hints: ["留意開頭的 /v/ 聲音。"],
    variantGroup: "g3-listen-v",
  }),
  q({
    id: "g3-review-letter-listening-04",
    skill: "letters",
    indicator: "能聽辨單一英文字母名稱",
    microSkill: "letter-listening",
    difficulty: 1,
    purpose: "review",
    modality: "audio",
    audioTranscript: "J",
    prompt: "Listen once. Pick the letter name you hear.",
    options: ["J", "G", "K"],
    answerIndex: 0,
    explanation: "音檔念的是字母 J。",
    hints: ["J 的尾音和 G 不同，完整聽到最後。"],
    variantGroup: "g3-listen-j",
  }),
  q({
    id: "g3-review-letter-listening-05",
    skill: "letters",
    indicator: "能分辨容易混淆的英文字母名稱",
    microSkill: "letter-listening",
    difficulty: 2,
    purpose: "practice",
    modality: "audio",
    audioTranscript: "G",
    prompt: "The robot says a letter. Which button should you press?",
    options: ["G", "J", "Z"],
    answerIndex: 0,
    explanation: "音檔念的是 G；J 和 Z 的起始聲音不同。",
    hints: ["把三個選項各念一次，再比對音檔。"],
    variantGroup: "g3-listen-g",
  }),
  q({
    id: "g3-review-letter-listening-06",
    skill: "letters",
    indicator: "能聽辨兩個英文字母的先後順序",
    microSkill: "letter-listening",
    difficulty: 2,
    purpose: "practice",
    modality: "audio",
    audioTranscript: "B, D",
    prompt: "Listen to two letters. Which option has the same order?",
    options: ["B D", "D B", "P D"],
    answerIndex: 0,
    explanation: "音檔依序念 B、D，所以正確順序是 B D。",
    hints: ["用手指先記第一個字母，再聽第二個。"],
    variantGroup: "g3-listen-bd-sequence",
  }),
  q({
    id: "g3-review-letter-listening-07",
    skill: "letters",
    indicator: "能聽辨三個英文字母組成的代碼",
    microSkill: "letter-listening",
    difficulty: 2,
    purpose: "review",
    modality: "audio",
    audioTranscript: "A, T, P",
    prompt: "Listen to the three-letter code. Which code is correct?",
    options: ["A T P", "A P T", "E T P"],
    answerIndex: 0,
    explanation: "音檔的順序是 A、T、P。",
    hints: ["把代碼分成第一、第二、第三個位置來聽。"],
    variantGroup: "g3-listen-atp-code",
  }),
  q({
    id: "g3-review-letter-listening-08",
    skill: "letters",
    indicator: "能依序聽辨並排列多個字母",
    microSkill: "letter-listening",
    difficulty: 3,
    purpose: "boss",
    modality: "audio",
    audioTranscript: "L, T, N",
    prompt: "Listen to three letters in order. Which set matches what you heard?",
    options: ["L T N", "L N T", "T L N"],
    answerIndex: 0,
    explanation: "音檔依序念 L、T、N，順序和字母都要對。",
    hints: ["先記住第一個字母，再依序聽完整段音檔。"],
    variantGroup: "g3-listen-boss-ltn",
  }),

  q({
    id: "g3-review-letter-writing-01",
    skill: "letters",
    indicator: "能辨認字母大小寫的正確書寫順序",
    microSkill: "letter-writing",
    difficulty: 1,
    purpose: "practice",
    prompt: "Write capital D first and lowercase d second. Which is correct?",
    options: ["D d", "b D", "B b"],
    answerIndex: 0,
    explanation: "題目要求先大寫 D，再小寫 d，所以是 D d。",
    hints: ["先找第一個是大寫 D 的選項。"],
    variantGroup: "g3-write-d-order",
  }),
  q({
    id: "g3-review-letter-writing-02",
    skill: "letters",
    indicator: "能正確抄寫英文字母大小寫",
    microSkill: "letter-writing",
    difficulty: 1,
    purpose: "practice",
    prompt: "The model is Gg. Which line copies it correctly?",
    options: ["Gg", "Gq", "Qq"],
    answerIndex: 0,
    explanation: "Gg 完整保留了原本的大寫 G 和小寫 g。",
    hints: ["逐一比對第一個和第二個字母。"],
    variantGroup: "g3-write-copy-gg",
  }),
  q({
    id: "g3-review-letter-writing-03",
    skill: "letters",
    indicator: "能以正確大小寫形式完成字母序列",
    microSkill: "letter-writing",
    difficulty: 1,
    purpose: "rescue",
    prompt: "Complete the writing line: Aa, Bb, __.",
    options: ["Cc", "Cq", "Dd"],
    answerIndex: 0,
    explanation: "Aa、Bb 後面是 Cc，而且每組都先大寫再小寫。",
    hints: ["先想 B 的下一個字母，再看大小寫順序。"],
    variantGroup: "g3-write-sequence-cc",
  }),
  q({
    id: "g3-review-letter-writing-04",
    skill: "letters",
    indicator: "能依指示選出正確的字母書寫形式",
    microSkill: "letter-writing",
    difficulty: 1,
    purpose: "practice",
    prompt: "The teacher asks for lowercase f. Which answer describes it?",
    options: ["the small f", "the small t", "the big F"],
    answerIndex: 0,
    explanation: "lowercase f 指的是小寫字母 f。",
    hints: ["lowercase 就是小寫。"],
    variantGroup: "g3-write-lower-f",
  }),
  q({
    id: "g3-review-letter-writing-05",
    skill: "letters",
    indicator: "能依多步驟指示書寫英文字母",
    microSkill: "letter-writing",
    difficulty: 2,
    purpose: "practice",
    prompt: "Write capital F, lowercase f, then capital T. Which line is correct?",
    options: ["F f T", "P f T", "F t T"],
    answerIndex: 0,
    explanation: "依序是大寫 F、小寫 f、大寫 T，所以答案是 F f T。",
    hints: ["把三個要求各對應到一個位置。"],
    variantGroup: "g3-write-fft",
  }),
  q({
    id: "g3-review-letter-writing-06",
    skill: "letters",
    indicator: "能找出字母抄寫中的大小寫錯誤",
    microSkill: "letter-writing",
    difficulty: 2,
    purpose: "review",
    prompt: "The model is Pp Rr. Which copy needs no correction?",
    options: ["Pp Rr", "Pq Rr", "Pp Kk"],
    answerIndex: 0,
    explanation: "Pp Rr 與範例完全相同，字母和大小寫順序都正確。",
    hints: ["先比 Pp，再比 Rr。"],
    variantGroup: "g3-write-copy-pprr",
  }),
  q({
    id: "g3-review-letter-writing-07",
    skill: "letters",
    indicator: "能依字母名稱與大小寫指示完成書寫",
    microSkill: "letter-writing",
    difficulty: 2,
    purpose: "review",
    prompt: "Which line follows: big N, small n, small m?",
    options: ["N n m", "M n m", "N m n"],
    answerIndex: 0,
    explanation: "big N 是 N，small n 是 n，small m 是 m。",
    hints: ["big 代表大寫，small 代表小寫。"],
    variantGroup: "g3-write-nnm",
  }),
  q({
    id: "g3-review-letter-writing-08",
    skill: "letters",
    indicator: "能依序書寫多組字母的大小寫形式",
    microSkill: "letter-writing",
    difficulty: 3,
    purpose: "boss",
    prompt: "Write capital G, lowercase g, capital I, lowercase i, in order. Which line is correct?",
    options: ["G g I i", "G g I l", "C g I i"],
    answerIndex: 0,
    explanation: "依序是大寫 G、小寫 g、大寫 I、小寫 i，四個位置都要對。",
    hints: ["把四個要求各自對應到一個位置，逐一核對。"],
    variantGroup: "g3-write-boss-ggii",
  }),

  q({
    id: "g3-review-phonological-awareness-01",
    skill: "phonics",
    indicator: "能辨識字詞的相同起始音",
    microSkill: "phonological-awareness",
    difficulty: 1,
    purpose: "practice",
    prompt: "Which word begins with the same sound as sun?",
    options: ["sit", "map", "fish"],
    answerIndex: 0,
    explanation: "sun 和 sit 都以 /s/ 開頭。",
    hints: ["只比較每個字的第一個聲音。"],
    variantGroup: "g3-onset-s",
  }),
  q({
    id: "g3-review-phonological-awareness-02",
    skill: "phonics",
    indicator: "能找出起始音不同的字詞",
    microSkill: "phonological-awareness",
    difficulty: 1,
    purpose: "practice",
    prompt: "Which word starts with a different sound?",
    options: ["dog", "map", "moon"],
    answerIndex: 0,
    explanation: "map 和 moon 都以 /m/ 開頭，dog 以 /d/ 開頭。",
    hints: ["先找出兩個開頭聲音相同的字。"],
    variantGroup: "g3-odd-onset-d",
  }),
  q({
    id: "g3-review-phonological-awareness-03",
    skill: "phonics",
    indicator: "能由聽覺辨識字詞的起始音",
    microSkill: "phonological-awareness",
    difficulty: 1,
    purpose: "rescue",
    modality: "audio",
    audioTranscript: "fish",
    prompt: "Listen. Which word begins with the same first sound?",
    options: ["fan", "van", "sun"],
    answerIndex: 0,
    explanation: "fish 和 fan 的第一個聲音都是 /f/。",
    hints: ["把 fish 拉長，只聽第一個聲音。"],
    variantGroup: "g3-onset-f",
  }),
  q({
    id: "g3-review-phonological-awareness-04",
    skill: "phonics",
    indicator: "能辨識字詞的相同結尾音",
    microSkill: "phonological-awareness",
    difficulty: 1,
    purpose: "practice",
    prompt: "Which word ends with the same sound as cat?",
    options: ["hat", "cap", "can"],
    answerIndex: 0,
    explanation: "cat 和 hat 都以 /t/ 結尾。",
    hints: ["只聽每個字最後一個聲音。"],
    variantGroup: "g3-rime-final-t",
  }),
  q({
    id: "g3-review-phonological-awareness-05",
    skill: "phonics",
    indicator: "能將相同起始音的字詞歸類",
    microSkill: "phonological-awareness",
    difficulty: 2,
    purpose: "practice",
    prompt: "Which pair belongs in the /b/ sound box?",
    options: ["ball and bed", "pig and pen", "cat and cup"],
    answerIndex: 0,
    explanation: "ball 和 bed 都以 /b/ 開頭。",
    hints: ["念每個單字的第一個聲音。"],
    variantGroup: "g3-sort-onset-b",
  }),
  q({
    id: "g3-review-phonological-awareness-06",
    skill: "phonics",
    indicator: "能辨識押韻的基礎字詞",
    microSkill: "phonological-awareness",
    difficulty: 2,
    purpose: "review",
    prompt: "Which word rhymes with pig?",
    options: ["wig", "pen", "sun"],
    answerIndex: 0,
    explanation: "pig 和 wig 都有相同的 /ɪg/ 韻尾。",
    hints: ["忽略第一個聲音，聽後面的部分。"],
    variantGroup: "g3-rhyme-ig",
  }),
  q({
    id: "g3-review-phonological-awareness-07",
    skill: "phonics",
    indicator: "能同時比較多個字詞的起始音與結尾音",
    microSkill: "phonological-awareness",
    difficulty: 3,
    purpose: "boss",
    prompt: "Which statement is true about map, moon, and sun?",
    options: [
      "map and moon share the first sound",
      "moon and sun share the first sound",
      "map and sun share the last sound",
    ],
    answerIndex: 0,
    explanation: "map 和 moon 都以 /m/ 開頭；其他兩個敘述都不正確。",
    hints: ["先比較三個字的第一個聲音，再檢查最後一個聲音。"],
    variantGroup: "g3-onset-m-analysis",
  }),

  q({
    id: "g3-review-cvc-decoding-01",
    skill: "phonics",
    indicator: "能將三個字母音合成 CVC 字詞",
    microSkill: "cvc-decoding",
    difficulty: 1,
    purpose: "practice",
    prompt: "Blend /d/ /ɒ/ /g/. Which word do you get?",
    options: ["dog", "dig", "dot"],
    answerIndex: 0,
    explanation: "/d/、/ɒ/、/g/ 合起來是 dog。",
    hints: ["先連 d-o，再加最後的 g。"],
    variantGroup: "g3-cvc-dog",
  }),
  q({
    id: "g3-review-cvc-decoding-02",
    skill: "phonics",
    indicator: "能辨識 CVC 字詞的短母音",
    microSkill: "cvc-decoding",
    difficulty: 1,
    purpose: "practice",
    prompt: "Which word has the short e sound /ɛ/?",
    options: ["hen", "hat", "hit"],
    answerIndex: 0,
    explanation: "hen 的中間字母 e 發短母音 /ɛ/。",
    hints: ["只比較三個單字中間的聲音。"],
    variantGroup: "g3-cvc-hen",
  }),
  q({
    id: "g3-review-cvc-decoding-03",
    skill: "phonics",
    indicator: "能辨識 CVC 字詞的結尾音",
    microSkill: "cvc-decoding",
    difficulty: 1,
    purpose: "rescue",
    prompt: "Which word ends with /p/?",
    options: ["map", "man", "mat"],
    answerIndex: 0,
    explanation: "map 的最後一個字母是 p，結尾音是 /p/。",
    hints: ["遮住前兩個字母，只看最後一個。"],
    variantGroup: "g3-cvc-final-p",
  }),
  q({
    id: "g3-review-cvc-decoding-04",
    skill: "phonics",
    indicator: "能聽辨基礎 CVC 字詞",
    microSkill: "cvc-decoding",
    difficulty: 1,
    purpose: "practice",
    modality: "audio",
    audioTranscript: "sun",
    prompt: "Listen. Which CVC word do you hear?",
    options: ["sun", "sit", "sum"],
    answerIndex: 0,
    explanation: "音檔念的是 sun，中間是短 u，結尾是 n。",
    hints: ["依序聽開頭、中間與結尾三個聲音。"],
    variantGroup: "g3-cvc-sun",
  }),
  q({
    id: "g3-review-cvc-decoding-05",
    skill: "phonics",
    indicator: "能在短句中依語意辨識 CVC 字詞",
    microSkill: "cvc-decoding",
    difficulty: 2,
    purpose: "practice",
    prompt: "A red ___ is on Ben's head. Which word completes the sentence?",
    options: ["hat", "hen", "hot"],
    answerIndex: 0,
    explanation: "戴在頭上的物品是 hat，句子意思也完整。",
    hints: ["先想 head 上可以放什麼，再拼讀選項。"],
    variantGroup: "g3-cvc-context-hat",
  }),
  q({
    id: "g3-review-cvc-decoding-06",
    skill: "phonics",
    indicator: "能以中間音辨識 CVC 最小對比字詞",
    microSkill: "cvc-decoding",
    difficulty: 2,
    purpose: "review",
    modality: "audio",
    audioTranscript: "pig, pen",
    prompt: "Listen to two words. Which option keeps the same order?",
    options: ["pig, pen", "pen, pig", "pig, pin"],
    answerIndex: 0,
    explanation: "音檔先念 pig，再念 pen；兩字的中間母音不同。",
    hints: ["先記第一個字的中間音，再聽第二個。"],
    variantGroup: "g3-cvc-pig-pen-sequence",
  }),
  q({
    id: "g3-review-cvc-decoding-07",
    skill: "phonics",
    indicator: "能整合拼音與句意解讀 CVC 字詞",
    microSkill: "cvc-decoding",
    difficulty: 3,
    purpose: "boss",
    prompt:
      "Choose the two short-a CVC words that make a sensible sentence: The ___ can sit on the ___.",
    options: ["cat, mat", "hen, bed", "dog, log"],
    answerIndex: 0,
    explanation: "cat 和 mat 都是短 a 的 CVC 字，且 The cat can sit on the mat. 句意合理。",
    hints: ["先檢查兩個字的中間音都是短 a，再讀完整句子。"],
    variantGroup: "g3-cvc-cat-mat-context",
  }),
];
