import { pilotQuestion, type PilotQuestionSeed } from "../pilot/pilot-factory";

const q = (seed: Omit<PilotQuestionSeed, "grade">) => pilotQuestion({ grade: 5, ...seed });

const weatherListeningQuestions = [
  q({
    id: "g5-review-weather-01",
    skill: "comprehension",
    indicator: "能從簡短播報辨認晴朗天氣",
    microSkill: "weather-listening",
    difficulty: 1,
    purpose: "diagnostic",
    modality: "audio",
    audioTranscript: "Good morning! It is sunny and warm today.",
    prompt: "Listen to the morning report. Which weather card should Mia choose?",
    options: ["Rainy and cold", "Sunny and warm", "Cloudy and cool", "Windy and snowy"],
    answerIndex: 1,
    explanation: "播報同時出現 sunny 和 warm，因此要選晴朗又溫暖的天氣卡。",
    hints: ["先聽描述天空的字，再聽表示溫度的字。"],
    variantGroup: "g5-review-weather-sunny-warm",
  }),
  q({
    id: "g5-review-weather-02",
    skill: "comprehension",
    indicator: "能依天氣訊息選擇合適物品",
    microSkill: "weather-listening",
    difficulty: 1,
    purpose: "practice",
    modality: "audio",
    audioTranscript: "It will rain this afternoon, Noah. Take an umbrella to school.",
    prompt: "Listen to Noah's mother. What should Noah take to school?",
    options: ["An umbrella", "A sun hat", "A baseball glove", "A lunch box"],
    answerIndex: 0,
    explanation: "媽媽說下午會下雨，並直接提醒 Noah 帶 an umbrella。",
    hints: ["留意 Take 後面接的是哪一樣物品。"],
    variantGroup: "g5-review-weather-rain-umbrella",
  }),
  q({
    id: "g5-review-weather-03",
    skill: "comprehension",
    indicator: "能聽懂有風的戶外情境",
    microSkill: "weather-listening",
    difficulty: 1,
    purpose: "practice",
    modality: "audio",
    audioTranscript: "The wind is strong at the playground. Hold on to your hat.",
    prompt: "Listen. How is the weather at the playground?",
    options: ["It is windy.", "It is foggy.", "It is sunny.", "It is rainy."],
    answerIndex: 0,
    explanation: "strong wind 表示風很強，所以符合 windy 的天氣描述。",
    hints: ["wind 和 windy 是同一組字族，注意它們的共同部分。"],
    variantGroup: "g5-review-weather-strong-wind",
  }),
  q({
    id: "g5-review-weather-04",
    skill: "comprehension",
    indicator: "能從天空描述判斷多雲天氣",
    microSkill: "weather-listening",
    difficulty: 1,
    purpose: "practice",
    modality: "audio",
    audioTranscript: "There are many gray clouds in the sky. I cannot see the bright sun.",
    prompt: "Listen to the sky description. Which word best describes the weather?",
    options: ["Cloudy", "Stormy", "Hot", "Snowy"],
    answerIndex: 0,
    explanation: "天空有許多灰雲而且看不到亮太陽，最符合 cloudy。",
    hints: ["把 gray clouds 和四個天氣字配對。"],
    variantGroup: "g5-review-weather-gray-clouds",
  }),
  q({
    id: "g5-review-weather-05",
    skill: "comprehension",
    indicator: "能比較同一天不同時段的溫度",
    microSkill: "weather-listening",
    difficulty: 2,
    purpose: "rescue",
    modality: "audio",
    audioTranscript: "It is cold in the morning, but it will be warm after twelve o'clock.",
    prompt: "Listen to the forecast. When will the weather be warm?",
    options: ["After twelve o'clock", "Early in the morning", "Before breakfast", "All night"],
    answerIndex: 0,
    explanation: "but 後面的訊息說 after twelve o'clock 會變暖，因此答案是中午十二點後。",
    hints: ["聽到 but 時，後半句通常會提供不同的新訊息。"],
    variantGroup: "g5-review-weather-time-change",
  }),
  q({
    id: "g5-review-weather-06",
    skill: "comprehension",
    indicator: "能依天氣變化理解活動地點調整",
    microSkill: "weather-listening",
    difficulty: 2,
    purpose: "review",
    modality: "audio",
    audioTranscript: "It is raining now, so our class picnic will be in the school gym, not in the park.",
    prompt: "Listen to the announcement. Where will the class have its picnic?",
    options: ["In the school gym", "In the city park", "Beside the river", "On the playground"],
    answerIndex: 0,
    explanation: "因為正在下雨，廣播把野餐地點改到 school gym，並排除 park。",
    hints: ["找出 so 後面提到的新地點，並注意 not in the park。"],
    variantGroup: "g5-review-weather-picnic-gym",
  }),
  q({
    id: "g5-review-weather-07",
    skill: "comprehension",
    indicator: "能整合兩日預報安排合適活動",
    microSkill: "weather-listening",
    difficulty: 3,
    purpose: "boss",
    modality: "audio",
    audioTranscript: "Saturday will be sunny and dry. Sunday will be rainy and windy. Ella wants to ride her bike on a dry day.",
    prompt: "Listen to the weekend forecast. Which plan is best for Ella?",
    options: ["Ride her bike on Saturday", "Ride her bike on Sunday", "Wait for Sunday evening rain", "Choose the windiest time on Sunday"],
    answerIndex: 0,
    explanation: "Ella 要在乾燥的日子騎車；只有 Saturday 被描述為 sunny and dry。",
    hints: ["先找 dry 出現在哪一天，再核對 Ella 想做的活動。"],
    variantGroup: "g5-review-weather-weekend-plan",
  }),
];

const imageSentenceQuestions = [
  q({
    id: "g5-review-image-01",
    skill: "comprehension",
    indicator: "能以簡單現在進行式描述圖片動作",
    microSkill: "image-sentence-meaning",
    difficulty: 1,
    purpose: "diagnostic",
    modality: "image",
    imageScene: "girl-feeding-fish-by-pond",
    imageAlt: "池塘邊的人物與動物情境圖，請觀察圖片後選句子",
    prompt: "Look at the pond picture. Which sentence matches it?",
    options: ["The girl is feeding the fish.", "The girl is catching a bird.", "The girl is washing a car.", "The girl is drawing a tree."],
    answerIndex: 0,
    explanation: "圖中女孩把飼料撒向池塘裡的魚，所以是 feeding the fish。",
    hints: ["觀察女孩手上的食物正撒向哪些動物。"],
    variantGroup: "g5-review-image-feed-fish",
  }),
  q({
    id: "g5-review-image-02",
    skill: "comprehension",
    indicator: "能連結天氣線索與圖片中的人物行動",
    microSkill: "image-sentence-meaning",
    difficulty: 1,
    purpose: "practice",
    modality: "image",
    imageScene: "boy-closing-window-during-rain",
    imageAlt: "雨天室內的人物與門窗情境圖，請觀察圖片後作答",
    prompt: "Look at the rainy-day picture. What is the boy doing?",
    options: ["He is closing the window.", "He is opening the door.", "He is cleaning the floor.", "He is carrying a chair."],
    answerIndex: 0,
    explanation: "雨從窗外飄進來，男孩正在把 window 關起來，因此是 closing。",
    hints: ["先找男孩雙手碰到的物品，再判斷它要開或關。"],
    variantGroup: "g5-review-image-close-window",
  }),
  q({
    id: "g5-review-image-03",
    skill: "comprehension",
    indicator: "能辨認圖片中的家庭用餐情境",
    microSkill: "image-sentence-meaning",
    difficulty: 1,
    purpose: "practice",
    modality: "image",
    imageScene: "family-eating-breakfast-at-table",
    imageAlt: "家庭成員與餐桌物品的情境圖，請觀察圖片後選出敘述",
    prompt: "Look at the family picture. Which statement is true?",
    options: ["They are eating breakfast.", "They are planting flowers.", "They are waiting for a train.", "They are playing basketball."],
    answerIndex: 0,
    explanation: "桌上有早晨常見的吐司、牛奶和水果，全家正在 eating breakfast。",
    hints: ["利用桌上的食物和早晨光線判斷這是哪一種活動。"],
    variantGroup: "g5-review-image-family-breakfast",
  }),
  q({
    id: "g5-review-image-04",
    skill: "comprehension",
    indicator: "能理解圖片中的數量與位置關係",
    microSkill: "image-sentence-meaning",
    difficulty: 1,
    purpose: "practice",
    modality: "image",
    imageScene: "two-dogs-sleeping-under-table",
    imageAlt: "桌子與動物的室內情境圖，請核對數量與位置後作答",
    prompt: "Look carefully under the table. Which sentence is correct?",
    options: ["Two dogs are sleeping under the table.", "One dog is jumping over the table.", "Two cats are sitting on the table.", "Three dogs are running beside the table."],
    answerIndex: 0,
    explanation: "圖片顯示兩隻狗都在桌子下方睡覺，數量、動物和位置都要吻合。",
    hints: ["依序核對 how many、what animal、where 三項線索。"],
    variantGroup: "g5-review-image-dogs-under-table",
  }),
  q({
    id: "g5-review-image-05",
    skill: "comprehension",
    indicator: "能從場所與物件推論人物目的",
    microSkill: "image-sentence-meaning",
    difficulty: 2,
    purpose: "rescue",
    modality: "image",
    imageScene: "child-choosing-books-in-library",
    imageAlt: "公共室內空間中的人物與物品情境圖，請根據圖片推測人物目的",
    prompt: "Look at the library scene. Why is the child standing by the shelf?",
    options: ["The child is choosing books to read.", "The child is ordering lunch.", "The child is fixing a bicycle.", "The child is watering vegetables."],
    answerIndex: 0,
    explanation: "地點是 library，孩子拿著書查看書名，合理目的就是 choosing books to read。",
    hints: ["把場所 library 和孩子手上的物品一起思考。"],
    variantGroup: "g5-review-image-library-choice",
  }),
  q({
    id: "g5-review-image-06",
    skill: "comprehension",
    indicator: "能整合圖片中的時間、地點與行動",
    microSkill: "image-sentence-meaning",
    difficulty: 2,
    purpose: "review",
    modality: "image",
    imageScene: "children-waiting-for-bus-at-seven-thirty",
    imageAlt: "交通場站中的人物與時鐘情境圖，請核對人物、時間與行動",
    prompt: "Study the bus-stop picture. Which sentence gives all the important details?",
    options: ["Three children are waiting for the bus at 7:30.", "Two teachers are leaving the train at 6:30.", "Three children are riding bikes at 8:30.", "One child is sleeping beside a car at 7:00."],
    answerIndex: 0,
    explanation: "圖中有三位孩子、公車站與 7:30；第一句同時符合人物、行動和時間。",
    hints: ["圈出人數、交通工具和時鐘，再逐項刪除不合的選項。"],
    variantGroup: "g5-review-image-bus-time",
  }),
  q({
    id: "g5-review-image-07",
    skill: "comprehension",
    indicator: "能依公共標誌理解圖片人物的正確行為",
    microSkill: "image-sentence-meaning",
    difficulty: 2,
    purpose: "boss",
    modality: "image",
    imageScene: "boy-walking-bike-past-no-bikes-sign",
    imageAlt: "公園入口的標誌與人物情境圖，請依兩者關係選出敘述",
    prompt: "Look at the park sign and the boy. Which sentence best explains the scene?",
    options: ["He gets off his bike and walks because riding is not allowed.", "He rides faster because the path is clear.", "He leaves the bike because it is broken.", "He races his friend because the park is closing."],
    answerIndex: 0,
    explanation: "禁止騎車標誌說明 riding is not allowed，男孩下車牽行是在遵守規定。",
    hints: ["先讀懂被斜線劃掉的腳踏車符號，再看男孩是否還坐在車上。"],
    variantGroup: "g5-review-image-no-bikes-sign",
  }),
];

const adjectiveQuestions = [
  q({
    id: "g5-review-adjective-01",
    skill: "vocabulary",
    indicator: "能以觸感形容詞描述物品狀態",
    microSkill: "adjectives",
    difficulty: 1,
    purpose: "diagnostic",
    prompt: "The ice cream was left in the sun. Now it is easy to press and no longer firm. It feels ___.",
    options: ["soft", "sharp", "heavy", "dry"],
    answerIndex: 0,
    explanation: "冰淇淋受熱後不再堅實而容易壓下，觸感應是 soft。",
    hints: ["找出和 firm 意思相反、可描述觸感的字。"],
    variantGroup: "g5-review-adjective-soft-ice-cream",
  }),
  q({
    id: "g5-review-adjective-02",
    skill: "vocabulary",
    indicator: "能依重量線索選擇合適形容詞",
    microSkill: "adjectives",
    difficulty: 1,
    purpose: "practice",
    prompt: "Tina's schoolbag has only one notebook inside, so she can lift it with one finger. The bag is ___.",
    options: ["light", "deep", "slow", "noisy"],
    answerIndex: 0,
    explanation: "書包幾乎是空的，甚至可用一根手指提起，表示重量很 light。",
    hints: ["從 lift it with one finger 推想書包是重還是輕。"],
    variantGroup: "g5-review-adjective-light-bag",
  }),
  q({
    id: "g5-review-adjective-03",
    skill: "vocabulary",
    indicator: "能使用比較概念理解長短形容詞",
    microSkill: "adjectives",
    difficulty: 1,
    purpose: "practice",
    prompt: "Ruler A is 30 centimeters. Ruler B is 15 centimeters. Ruler A is ___ than Ruler B.",
    options: ["longer", "younger", "quieter", "cleaner"],
    answerIndex: 0,
    explanation: "30 公分大於 15 公分，兩把尺比較的是長度，所以 A is longer。",
    hints: ["題目單位是 centimeters，應選和長度有關的比較字。"],
    variantGroup: "g5-review-adjective-longer-ruler",
  }),
  q({
    id: "g5-review-adjective-04",
    skill: "vocabulary",
    indicator: "能從尺寸線索辨認大小形容詞",
    microSkill: "adjectives",
    difficulty: 1,
    purpose: "practice",
    prompt: "The kitten can sit inside one of Grandpa's hands. Which adjective describes the kitten?",
    options: ["tiny", "angry", "late", "famous"],
    answerIndex: 0,
    explanation: "小貓能坐進一隻手掌，尺寸非常小，最精確的形容詞是 tiny。",
    hints: ["用 one hand 當作比例尺，判斷小貓的大小。"],
    variantGroup: "g5-review-adjective-tiny-kitten",
  }),
  q({
    id: "g5-review-adjective-05",
    skill: "vocabulary",
    indicator: "能依聲音情境選擇形容詞",
    microSkill: "adjectives",
    difficulty: 1,
    purpose: "rescue",
    prompt: "The baby is sleeping, and nobody is talking or playing music. The room is ___.",
    options: ["quiet", "crowded", "bright", "sweet"],
    answerIndex: 0,
    explanation: "沒有人說話也沒有音樂，房間的聲音狀態就是 quiet。",
    hints: ["想想 nobody is talking 表示房間有沒有聲音。"],
    variantGroup: "g5-review-adjective-quiet-room",
  }),
  q({
    id: "g5-review-adjective-06",
    skill: "comprehension",
    indicator: "能依兩項特徵比較路線難易",
    microSkill: "adjectives",
    difficulty: 2,
    purpose: "review",
    prompt: "Trail A is short and flat. Trail B is long and steep. Which trail is easier for a new hiker?",
    options: ["Trail A, because it is short and flat.", "Trail B, because it is long and steep.", "Trail A, because it is dark and wet.", "Trail B, because it is short and flat."],
    answerIndex: 0,
    explanation: "對新手而言，short and flat 比 long and steep 容易，因此應選 Trail A。",
    hints: ["分別比較 short/long 與 flat/steep 兩組相反特徵。"],
    variantGroup: "g5-review-adjective-hiking-trails",
  }),
  q({
    id: "g5-review-adjective-07",
    skill: "comprehension",
    indicator: "能整合物品狀態與材質選擇形容詞",
    microSkill: "adjectives",
    difficulty: 2,
    purpose: "boss",
    prompt: "Bottle A is old and cracked. Bottle B is new and made of steel. Mei needs a bottle that will not break easily. Which description helps her choose?",
    options: ["Bottle B is strong and useful.", "Bottle A is weak but useful.", "Bottle B is soft and broken.", "Bottle A is new and strong."],
    answerIndex: 0,
    explanation: "Mei 需要不易破的水壺；新的鋼製 Bottle B 最符合 strong and useful。",
    hints: ["把 will not break easily 換成一個表示堅固的形容詞。"],
    variantGroup: "g5-review-adjective-strong-bottle",
  }),
];

const ageAndCanQuestions = [
  q({
    id: "g5-review-age-can-01",
    skill: "grammar",
    indicator: "能從自我介紹回答年齡問句",
    microSkill: "age-and-can",
    difficulty: 1,
    purpose: "diagnostic",
    prompt: "Owen says, 'I am eleven years old.' How old is Owen?",
    options: ["He is eleven.", "He is seven.", "He can count to eleven.", "He has eleven pencils."],
    answerIndex: 0,
    explanation: "Owen 說 I am eleven years old，改用第三人稱回答就是 He is eleven。",
    hints: ["How old 只問年齡，把 I 換成 He 後保留數字。"],
    variantGroup: "g5-review-age-owen-eleven",
  }),
  q({
    id: "g5-review-age-can-02",
    skill: "grammar",
    indicator: "能依肯定與否定能力敘述選出正確句子",
    microSkill: "age-and-can",
    difficulty: 1,
    purpose: "practice",
    prompt: "Lina can play the violin, but she cannot play the drums. What can Lina do?",
    options: ["She can play the violin.", "She can play the drums.", "She cannot play any instrument.", "She can only listen to music."],
    answerIndex: 0,
    explanation: "前半句明確說 Lina can play the violin；but 後面是否定另一種樂器。",
    hints: ["先找 can 後面的樂器，別把 cannot 後面的 drums 選進來。"],
    variantGroup: "g5-review-can-lina-violin",
  }),
  q({
    id: "g5-review-age-can-03",
    skill: "classroom_english",
    indicator: "能以 can 回應日常能力問句",
    microSkill: "age-and-can",
    difficulty: 1,
    purpose: "practice",
    prompt: "Your brother asks, 'Can you ride a bike?' You want to say yes. What should you answer?",
    options: ["Yes, I can.", "Yes, I am.", "Yes, you do.", "Yes, I ride."],
    answerIndex: 0,
    explanation: "Can you ...? 的肯定簡答要把 you 換成 I，使用 Yes, I can。",
    hints: ["問句用 can 開頭，簡答也要保留 can。"],
    variantGroup: "g5-review-can-bike-reply",
  }),
  q({
    id: "g5-review-age-can-04",
    skill: "comprehension",
    indicator: "能運用年齡差推算人物年齡",
    microSkill: "age-and-can",
    difficulty: 1,
    purpose: "practice",
    prompt: "I am ten years old. My sister is two years older than I am. How old is my sister?",
    options: ["She is twelve.", "She is eight.", "She is ten.", "She is twenty."],
    answerIndex: 0,
    explanation: "姐姐比十歲大兩歲，10 + 2 = 12，所以 She is twelve。",
    hints: ["older than 表示年齡要往上加，不是往下減。"],
    variantGroup: "g5-review-age-older-sister",
  }),
  q({
    id: "g5-review-age-can-05",
    skill: "comprehension",
    indicator: "能整合人物年齡與兩項能力資訊",
    microSkill: "age-and-can",
    difficulty: 2,
    purpose: "rescue",
    prompt: "Ken is eleven. He can swim across the pool, but he cannot dive. Which sentence is true?",
    options: ["Ken is eleven and can swim.", "Ken is twelve and can dive.", "Ken is eleven and can dive.", "Ken is ten and cannot swim."],
    answerIndex: 0,
    explanation: "原文同時支持 Ken 十一歲和會游泳；dive 則被 cannot 否定。",
    hints: ["每個選項都分成『年齡』與『能力』兩部分，兩部分都要正確。"],
    variantGroup: "g5-review-age-can-ken-swim",
  }),
  q({
    id: "g5-review-age-can-06",
    skill: "grammar",
    indicator: "能配對能力問句與帶轉折的完整回答",
    microSkill: "age-and-can",
    difficulty: 2,
    purpose: "review",
    prompt: "Ava can make sandwiches, but she cannot cook noodles. Which question and answer match Ava's abilities?",
    options: ["Can Ava make sandwiches? Yes, she can.", "Can Ava cook noodles? Yes, she can.", "Can Ava make sandwiches? No, she can't.", "Can Ava cook noodles? Yes, he can."],
    answerIndex: 0,
    explanation: "Ava 會做三明治，因此第一組問答的動作、肯定回答和代名詞都正確。",
    hints: ["同時檢查 can/cannot、Yes/No，以及 Ava 要用 she。"],
    variantGroup: "g5-review-can-ava-food",
  }),
  q({
    id: "g5-review-age-can-07",
    skill: "comprehension",
    indicator: "能依年齡限制與能力條件判斷資格",
    microSkill: "age-and-can",
    difficulty: 2,
    purpose: "boss",
    prompt: "The climbing class is for children aged 10 to 12 who can follow safety directions. Bo is eleven and can follow every direction. Can Bo join?",
    options: ["Yes, because his age and ability meet both rules.", "No, because eleven is younger than ten.", "No, because the class is only for twelve-year-olds.", "Yes, because safety directions are not important."],
    answerIndex: 0,
    explanation: "Bo 十一歲，符合 10 到 12 歲；他也能遵守安全指示，所以兩項規則都達成。",
    hints: ["先檢查 11 是否在 10–12 之間，再檢查 can 後面的能力。"],
    variantGroup: "g5-review-age-can-climbing-rules",
  }),
];

const shortDialogueQuestions = [
  q({
    id: "g5-review-dialogue-01",
    skill: "classroom_english",
    indicator: "能在借用文具時選擇合宜回應",
    microSkill: "short-dialogue",
    difficulty: 1,
    purpose: "diagnostic",
    prompt: "Nina: May I borrow your eraser? Sam: ___",
    options: ["Sure. Here you are.", "No, I am an eraser.", "It is under the rain.", "I borrow Nina yesterday."],
    answerIndex: 0,
    explanation: "對方有禮貌地借橡皮擦，同意時可說 Sure，並用 Here you are 遞出物品。",
    hints: ["想像 Sam 願意把橡皮擦交給 Nina 時會說什麼。"],
    variantGroup: "g5-review-dialogue-borrow-eraser",
  }),
  q({
    id: "g5-review-dialogue-02",
    skill: "comprehension",
    indicator: "能從短對話取得課程時間",
    microSkill: "short-dialogue",
    difficulty: 1,
    purpose: "practice",
    prompt: "A: What time does art class start? B: It starts at nine twenty. When is art class?",
    options: ["At 9:20", "At 8:20", "At 9:02", "At 10:20"],
    answerIndex: 0,
    explanation: "nine twenty 對應數字時間 9:20，不能把 twenty 聽成 02。",
    hints: ["先找 nine 對應小時，再找 twenty 對應分鐘。"],
    variantGroup: "g5-review-dialogue-art-time",
  }),
  q({
    id: "g5-review-dialogue-03",
    skill: "classroom_english",
    indicator: "能依身體需求接續簡短對話",
    microSkill: "short-dialogue",
    difficulty: 1,
    purpose: "practice",
    prompt: "A: You look thirsty. B: Yes, I am. A: ___",
    options: ["Let's get some water.", "Let's close our books forever.", "Let's wear two winter coats.", "Let's count the classroom windows."],
    answerIndex: 0,
    explanation: "thirsty 表示口渴，最自然的下一步是提議去拿水。",
    hints: ["找出能直接解決 thirsty 需求的行動。"],
    variantGroup: "g5-review-dialogue-thirsty-water",
  }),
  q({
    id: "g5-review-dialogue-04",
    skill: "classroom_english",
    indicator: "能對感謝語做合宜回應",
    microSkill: "short-dialogue",
    difficulty: 1,
    purpose: "practice",
    prompt: "A: Thank you for helping me carry these books. B: ___",
    options: ["You're welcome.", "Good night yesterday.", "These books can swim.", "I am twelve pencils."],
    answerIndex: 0,
    explanation: "別人說 Thank you 時，You’re welcome 是最合宜的禮貌回應。",
    hints: ["回想接受別人道謝時常用的固定句型。"],
    variantGroup: "g5-review-dialogue-thanks-books",
  }),
  q({
    id: "g5-review-dialogue-05",
    skill: "comprehension",
    indicator: "能從方向對話定位校園場所",
    microSkill: "short-dialogue",
    difficulty: 2,
    purpose: "rescue",
    prompt: "A: Where is the science room? B: Go upstairs, turn left, and look next to the computer room. Where should A look?",
    options: ["Upstairs, beside the computer room", "Downstairs, inside the cafeteria", "Outside, behind the playground", "Upstairs, across from the library entrance"],
    answerIndex: 0,
    explanation: "指示包含 upstairs、turn left 與 next to the computer room，第一個地點完整保留關鍵資訊。",
    hints: ["依序記住樓層和相鄰地點；next to 就是 beside。"],
    variantGroup: "g5-review-dialogue-science-room",
  }),
  q({
    id: "g5-review-dialogue-06",
    skill: "comprehension",
    indicator: "能理解點餐對話中的缺貨與替代選擇",
    microSkill: "short-dialogue",
    difficulty: 2,
    purpose: "review",
    prompt: "Server: Sorry, there is no soup today. We have noodles or rice. Kai: Then I'll have the noodles, please. What does Kai order?",
    options: ["Noodles", "Soup", "Rice", "A sandwich"],
    answerIndex: 0,
    explanation: "soup 缺貨後，Kai 明確改說 I'll have the noodles，所以最後點的是麵。",
    hints: ["以 Kai 最後一句為準，不要選對話前面被說沒有的餐點。"],
    variantGroup: "g5-review-dialogue-order-noodles",
  }),
  q({
    id: "g5-review-dialogue-07",
    skill: "comprehension",
    indicator: "能整合短對話中的時間與路程資訊",
    microSkill: "short-dialogue",
    difficulty: 3,
    purpose: "boss",
    prompt: "Coach: Practice ends at 3:40. The lost-and-found office closes at 4:00. It takes ten minutes to walk there. Lia: Great, I can get my umbrella. When will Lia arrive?",
    options: ["At 3:50, before the office closes", "At 4:10, after the office closes", "At 3:30, before practice ends", "At 4:00, after a twenty-minute walk"],
    answerIndex: 0,
    explanation: "練習 3:40 結束，再走十分鐘是 3:50，早於辦公室 4:00 關門。",
    hints: ["把 10 分鐘加到 3:40，再和 4:00 比較。"],
    variantGroup: "g5-review-dialogue-office-time",
  }),
];

export const grade5ReviewCandidates = [
  ...weatherListeningQuestions,
  ...imageSentenceQuestions,
  ...adjectiveQuestions,
  ...ageAndCanQuestions,
  ...shortDialogueQuestions,
];
