import { pilotQuestion, type PilotQuestionSeed } from "@/content/pilot/pilot-factory";
import { questionSchema } from "@/domain/questions/question-schema";

type AnswerPosition = 0 | 1 | 2 | 3;

type ReviewCandidateSeed = Omit<
  PilotQuestionSeed,
  "grade" | "options" | "answerIndex"
> &
  Readonly<{
    correct: string;
    distractors: readonly [string, string, string];
    answerPosition: AnswerPosition;
  }>;

function candidate(seed: ReviewCandidateSeed) {
  const { correct, distractors, answerPosition, ...questionSeed } = seed;
  const optionCount = distractors.length + 1;
  const rotation =
    Array.from(seed.id).reduce((total, character) => total + character.charCodeAt(0), 0) %
    optionCount;
  const answerIndex = (answerPosition + rotation) % optionCount;
  const options = [...distractors];
  options.splice(answerIndex, 0, correct);

  return questionSchema.parse(
    pilotQuestion({
      grade: 4,
      ...questionSeed,
      options,
      answerIndex,
    }),
  );
}

export const grade4ReviewCandidates = [
  candidate({
    id: "g4-review-image-sentence-01",
    skill: "comprehension",
    indicator: "能依日常生活圖片選出相符的簡單句",
    microSkill: "image-sentence-match",
    difficulty: 1,
    purpose: "diagnostic",
    modality: "image",
    imageScene: "boy-feeding-dog-in-yard",
    imageAlt: "男孩和狗一起待在院子裡的生活情境圖",
    prompt: "Look at Ben and the dog in the yard. Which sentence matches the picture?",
    correct: "Ben is feeding the dog.",
    distractors: [
      "Ben is washing the dog.",
      "Ben is chasing the dog.",
      "Ben is drawing the dog.",
    ],
    answerPosition: 0,
    explanation: "圖中 Ben 正把食物倒進狗碗，所以相符的句子是 Ben is feeding the dog.",
    hints: ["找找看 Ben 手上的食物要放到哪裡。"],
    variantGroup: "g4-review-image-feeding-dog",
  }),
  candidate({
    id: "g4-review-image-sentence-02",
    skill: "comprehension",
    indicator: "能依早餐情境圖片辨認人物動作",
    microSkill: "image-sentence-match",
    difficulty: 1,
    purpose: "practice",
    modality: "image",
    imageScene: "girl-drinking-milk-at-breakfast",
    imageAlt: "女孩坐在早餐桌旁的日常情境圖",
    prompt: "Mei is at the breakfast table. Which sentence tells what she is doing?",
    correct: "Mei is drinking milk.",
    distractors: [
      "Mei is eating rice.",
      "Mei is washing a cup.",
      "Mei is opening a lunch box.",
    ],
    answerPosition: 1,
    explanation: "圖片中的 Mei 拿著杯子喝牛奶，因此 Mei is drinking milk. 描述正確。",
    hints: ["注意 Mei 拿在嘴邊的是杯子。"],
    variantGroup: "g4-review-image-breakfast-milk",
  }),
  candidate({
    id: "g4-review-image-sentence-03",
    skill: "comprehension",
    indicator: "能依多人活動圖片選出複數主詞句",
    microSkill: "image-sentence-match",
    difficulty: 1,
    purpose: "practice",
    modality: "image",
    imageScene: "two-girls-jumping-rope-on-playground",
    imageAlt: "兩位女孩在操場一起活動的情境圖",
    prompt: "Look at Ann and Joy on the playground. Which sentence matches the picture?",
    correct: "The girls are jumping rope.",
    distractors: [
      "The girls are playing basketball.",
      "The girls are reading a story.",
      "The girls are riding bicycles.",
    ],
    answerPosition: 2,
    explanation: "Ann 和 Joy 共同握著跳繩，所以要用複數句 The girls are jumping rope.",
    hints: ["兩個人要搭配 are，再觀察她們手上的長繩。"],
    variantGroup: "g4-review-image-jumping-rope",
  }),
  candidate({
    id: "g4-review-image-sentence-04",
    skill: "comprehension",
    indicator: "能依圖片辨認物品與位置關係",
    microSkill: "image-sentence-match",
    difficulty: 1,
    purpose: "practice",
    modality: "image",
    imageScene: "cat-under-chair-in-bedroom",
    imageAlt: "房間裡有一隻貓和一張椅子的情境圖",
    prompt: "Where is the cat in the bedroom picture? Choose the matching sentence.",
    correct: "The cat is under the chair.",
    distractors: [
      "The cat is on the chair.",
      "The cat is behind the bed.",
      "The cat is beside the window.",
    ],
    answerPosition: 3,
    explanation: "貓的位置在椅面下方，因此要用 under，完整句是 The cat is under the chair.",
    hints: ["先找到椅子，再看貓在椅子的上方還是下方。"],
    variantGroup: "g4-review-image-cat-position",
  }),
  candidate({
    id: "g4-review-image-sentence-05",
    skill: "comprehension",
    indicator: "能從多人情境圖片鎖定指定人物的動作",
    microSkill: "image-sentence-match",
    difficulty: 2,
    purpose: "rescue",
    modality: "image",
    imageScene: "family-picnic-dad-cutting-watermelon",
    imageAlt: "一家人在公園野餐並各自進行不同活動的情境圖",
    prompt: "The family is having a picnic. Which sentence correctly describes Dad?",
    correct: "Dad is cutting the watermelon.",
    distractors: [
      "Dad is pouring the orange juice.",
      "Dad is throwing a red ball.",
      "Dad is taking pictures of the trees.",
    ],
    answerPosition: 0,
    explanation: "野餐圖中爸爸手拿刀子切西瓜，故 Dad is cutting the watermelon. 是正確描述。",
    hints: ["題目只問 Dad，先不要被其他家人的動作干擾。"],
    variantGroup: "g4-review-image-picnic-dad",
  }),
  candidate({
    id: "g4-review-image-sentence-06",
    skill: "comprehension",
    indicator: "能整合教室圖片中的人物、動作與地點",
    microSkill: "image-sentence-match",
    difficulty: 2,
    purpose: "review",
    modality: "image",
    imageScene: "teacher-writing-monday-on-board",
    imageAlt: "老師和學生正在教室上課的情境圖",
    prompt: "Study the classroom picture. Which sentence is true about the teacher?",
    correct: "The teacher is writing on the board.",
    distractors: [
      "The teacher is opening the classroom door.",
      "The teacher is sitting beside a student.",
      "The teacher is carrying a box of books.",
    ],
    answerPosition: 1,
    explanation: "老師站在黑板前寫 Monday，因此 The teacher is writing on the board. 符合圖片。",
    hints: ["看看黑板上新出現了哪一個英文單字。"],
    variantGroup: "g4-review-image-teacher-board",
  }),
  candidate({
    id: "g4-review-image-sentence-07",
    skill: "comprehension",
    indicator: "能比對圖片中兩位人物同時進行的活動",
    microSkill: "image-sentence-match",
    difficulty: 3,
    purpose: "boss",
    modality: "image",
    imageScene: "boy-riding-bike-girl-flying-kite-in-park",
    imageAlt: "兩位孩子在公園分別進行戶外活動的情境圖",
    prompt: "Two children are in the park. Which sentence matches both actions in the picture?",
    correct: "The boy is riding a bike, and the girl is flying a kite.",
    distractors: [
      "The boy is flying a kite, and the girl is riding a bike.",
      "The boy is riding a bike, and the girl is kicking a ball.",
      "The boy is running, and the girl is holding a bicycle.",
    ],
    answerPosition: 2,
    explanation: "要同時配對兩個動作：男孩騎腳踏車，女孩放風箏，兩部分都正確的才是答案。",
    hints: ["先分別確認 boy 與 girl 的動作，再選兩句都吻合的選項。"],
    variantGroup: "g4-review-image-two-park-actions",
  }),

  candidate({
    id: "g4-review-affirmative-negative-01",
    skill: "grammar",
    indicator: "能辨認 be 動詞否定句的縮寫",
    microSkill: "affirmative-negative",
    difficulty: 1,
    purpose: "diagnostic",
    prompt: "Nina is not sad. Which contraction keeps exactly the same meaning?",
    correct: "Nina isn't sad.",
    distractors: ["Nina doesn't sad.", "Nina wasn't sad.", "Nina isn't tired."],
    answerPosition: 3,
    explanation: "is not 的現在式縮寫是 isn't，所以 Nina isn't sad. 與原句意思完全相同。",
    hints: ["把 is 和 not 合併，保留原來的形容詞 sad。"],
    variantGroup: "g4-review-negative-is-not",
  }),
  candidate({
    id: "g4-review-affirmative-negative-02",
    skill: "grammar",
    indicator: "能將複數 be 動詞肯定句改為否定句",
    microSkill: "affirmative-negative",
    difficulty: 1,
    purpose: "practice",
    prompt: "Change “The bags are heavy.” into a negative sentence.",
    correct: "The bags are not heavy.",
    distractors: [
      "The bags not are heavy.",
      "The bags do not heavy.",
      "The bag are not heavy.",
    ],
    answerPosition: 0,
    explanation: "複數主詞 bags 搭配 are，否定詞 not 放在 are 後面：The bags are not heavy.",
    hints: ["保留 are，接著在它後面加入 not。"],
    variantGroup: "g4-review-negative-are-not",
  }),
  candidate({
    id: "g4-review-affirmative-negative-03",
    skill: "grammar",
    indicator: "能辨認 can 的否定形式",
    microSkill: "affirmative-negative",
    difficulty: 1,
    purpose: "practice",
    prompt: "Kai can skate. Which sentence uses the correct negative form of can?",
    correct: "Kai cannot skate.",
    distractors: ["Kai can not skates.", "Kai isn't skate.", "Kai does not can skate."],
    answerPosition: 1,
    explanation: "can 的否定形式可寫成 cannot，後面的動詞仍用原形 skate。",
    hints: ["can 之後的動詞不加 s，否定可合寫成 cannot。"],
    variantGroup: "g4-review-negative-cannot",
  }),
  candidate({
    id: "g4-review-affirmative-negative-04",
    skill: "grammar",
    indicator: "能用 aren't 表達複數主詞的否定",
    microSkill: "affirmative-negative",
    difficulty: 1,
    purpose: "practice",
    prompt: "We are ready. Which sentence says that we are not ready?",
    correct: "We aren't ready.",
    distractors: ["We don't ready.", "We isn't ready.", "We aren't read."],
    answerPosition: 2,
    explanation: "We 要搭配 are，are not 可縮寫為 aren't，因此答案是 We aren't ready.",
    hints: ["先找出與 We 正確搭配的 be 動詞否定縮寫。"],
    variantGroup: "g4-review-negative-we-arent",
  }),
  candidate({
    id: "g4-review-affirmative-negative-05",
    skill: "grammar",
    indicator: "能依物品資訊理解一般動詞否定句",
    microSkill: "affirmative-negative",
    difficulty: 2,
    purpose: "rescue",
    prompt: "Mia owns a blue pen, but she has no red pen. Which sentence is true?",
    correct: "Mia does not have a red pen.",
    distractors: [
      "Mia does not has a red pen.",
      "Mia is not have a red pen.",
      "Mia does not have a blue pen.",
    ],
    answerPosition: 3,
    explanation: "Mia 沒有紅筆；第三人稱否定用 does not，後接原形 have。",
    hints: ["does not 後面的 has 要還原成 have，並核對筆的顏色。"],
    variantGroup: "g4-review-negative-does-not-have",
  }),
  candidate({
    id: "g4-review-affirmative-negative-06",
    skill: "grammar",
    indicator: "能從簡短公告找出正確否定資訊",
    microSkill: "affirmative-negative",
    difficulty: 2,
    purpose: "review",
    prompt: "A notice says: “The library is open on Monday. It is closed on Sunday.” Which sentence correctly reports Sunday?",
    correct: "The library isn't open on Sunday.",
    distractors: [
      "The library isn't closed on Sunday.",
      "The library doesn't open on Monday.",
      "The library aren't open on Sunday.",
    ],
    answerPosition: 0,
    explanation: "公告說星期日 closed，因此可改述為 The library isn't open on Sunday.",
    hints: ["closed 和 not open 表達相同狀態，主詞 library 是單數。"],
    variantGroup: "g4-review-negative-library-notice",
  }),
  candidate({
    id: "g4-review-affirmative-negative-07",
    skill: "grammar",
    indicator: "能整合短文能力資訊判斷正確否定句",
    microSkill: "affirmative-negative",
    difficulty: 3,
    purpose: "boss",
    prompt: "Owen can ride a bike and skate, but he cannot swim. Which sentence correctly describes Owen?",
    correct: "Owen cannot swim.",
    distractors: [
      "Owen cannot skate.",
      "Owen cannot ride a bike.",
      "Owen is not able to skate or ride.",
    ],
    answerPosition: 1,
    explanation: "短文只把 swim 放在 cannot 後面；騎車與溜冰都是 Owen 會做的事。",
    hints: ["把 can 後面的兩項與 cannot 後面的一項分開整理。"],
    variantGroup: "g4-review-negative-owen-abilities",
  }),

  candidate({
    id: "g4-review-this-that-01",
    skill: "grammar",
    indicator: "能用 this 指稱手邊的單數物品",
    microSkill: "this-that-questions",
    difficulty: 1,
    purpose: "diagnostic",
    prompt: "You are holding one cookie in your hand. ___ is the cookie I just picked up.",
    correct: "This",
    distractors: ["That", "These", "Those"],
    answerPosition: 2,
    explanation: "餅乾是單數而且就在手上，近處單數要用 This。",
    hints: ["先判斷一個還是多個，再看物品離說話者近不近。"],
    variantGroup: "g4-review-this-cookie-near",
  }),
  candidate({
    id: "g4-review-this-that-02",
    skill: "grammar",
    indicator: "能用 that 指稱遠處的單數物品",
    microSkill: "this-that-questions",
    difficulty: 1,
    purpose: "practice",
    prompt: "A bus is across the street, far from you. ___ is our bus.",
    correct: "That",
    distractors: ["This", "These", "They"],
    answerPosition: 3,
    explanation: "公車在街道另一側，距離說話者較遠且是單數，所以使用 That。",
    hints: ["far from you 是選擇 that 的關鍵線索。"],
    variantGroup: "g4-review-that-bus-far",
  }),
  candidate({
    id: "g4-review-this-that-03",
    skill: "grammar",
    indicator: "能針對近處單數物品提出 this 問句",
    microSkill: "this-that-questions",
    difficulty: 1,
    purpose: "practice",
    prompt: "A pencil is beside your hand. Which question asks about it correctly?",
    correct: "Is this your pencil?",
    distractors: ["Is that your pencil?", "Are this your pencil?", "Does this your pencil?"],
    answerPosition: 0,
    explanation: "鉛筆就在手邊，應使用近處單數 this，問句以 Is 開頭。",
    hints: ["beside your hand 表示近處，而且 pencil 是一枝。"],
    variantGroup: "g4-review-this-pencil-question",
  }),
  candidate({
    id: "g4-review-this-that-04",
    skill: "grammar",
    indicator: "能針對遠處單數事物提出 that 問句",
    microSkill: "this-that-questions",
    difficulty: 1,
    purpose: "practice",
    prompt: "You point to the moon high in the sky. Which question should you ask?",
    correct: "Is that the moon?",
    distractors: ["Is this the moon?", "Are that the moon?", "Does that the moon?"],
    answerPosition: 1,
    explanation: "月亮離說話者很遠，單數遠處問句應使用 Is that ...?",
    hints: ["high in the sky 告訴你物體不是在手邊。"],
    variantGroup: "g4-review-that-moon-question",
  }),
  candidate({
    id: "g4-review-this-that-05",
    skill: "grammar",
    indicator: "能依對話中的距離線索選擇 this",
    microSkill: "this-that-questions",
    difficulty: 1,
    purpose: "rescue",
    prompt: "A: Is ___ your lunch bag here beside me? B: Yes, it is.",
    correct: "this",
    distractors: ["that", "these", "they"],
    answerPosition: 2,
    explanation: "here beside me 表示袋子靠近說話者，且 lunch bag 是單數，所以填 this。",
    hints: ["圈出 here 和 beside me，這兩個詞都表示近處。"],
    variantGroup: "g4-review-this-lunch-bag-dialogue",
  }),
  candidate({
    id: "g4-review-this-that-06",
    skill: "grammar",
    indicator: "能依說話者視角選擇 this 問句",
    microSkill: "this-that-questions",
    difficulty: 2,
    purpose: "review",
    prompt: "Emma is holding Sam's book in her hand. What should Emma ask Sam?",
    correct: "Is this your book, Sam?",
    distractors: [
      "Is that your book, Sam?",
      "Are these your book, Sam?",
      "Does this your book, Sam?",
    ],
    answerPosition: 3,
    explanation: "書就在說話者 Emma 手中，因此 Emma 應從自己的視角說 Is this your book, Sam?",
    hints: ["距離要以開口說話的 Emma 為中心判斷。"],
    variantGroup: "g4-review-this-speaker-viewpoint",
  }),
  candidate({
    id: "g4-review-this-that-07",
    skill: "grammar",
    indicator: "能同時區分近處與遠處的單數指示詞",
    microSkill: "this-that-questions",
    difficulty: 2,
    purpose: "boss",
    prompt: "At a museum, a model car is beside you and a model plane is across the room. Complete: “___ is a model car, and ___ is a model plane.”",
    correct: "This; that",
    distractors: ["That; this", "This; these", "These; those"],
    answerPosition: 0,
    explanation: "身旁的單數模型車用 This，房間另一端的單數模型飛機用 that。",
    hints: ["先處理 beside you，再處理 across the room。"],
    variantGroup: "g4-review-this-that-museum",
  }),

  candidate({
    id: "g4-review-yes-no-01",
    skill: "classroom_english",
    indicator: "能依明確資訊回答 Is this ...?",
    microSkill: "yes-no-questions",
    difficulty: 1,
    purpose: "diagnostic",
    prompt: "The card shows a map. Is this a map?",
    correct: "Yes, it is.",
    distractors: ["No, it isn't.", "Yes, I am.", "Yes, they are."],
    answerPosition: 1,
    explanation: "題目已說卡片上是 map，因此肯定回答 Is this ...? 要用 Yes, it is.",
    hints: ["Is this 的肯定簡答保留 is，並用 it 代替物品。"],
    variantGroup: "g4-review-yes-no-map",
  }),
  candidate({
    id: "g4-review-yes-no-02",
    skill: "classroom_english",
    indicator: "能以第一人稱回答 Are you ...?",
    microSkill: "yes-no-questions",
    difficulty: 1,
    purpose: "practice",
    prompt: "You are ten years old. Are you ten?",
    correct: "Yes, I am.",
    distractors: ["Yes, you are.", "Yes, it is.", "No, I am not."],
    answerPosition: 2,
    explanation: "自己回答 Are you ...? 時，要把 you 換成 I；資訊相符，所以說 Yes, I am.",
    hints: ["回答自己的年齡時，主詞要從 you 改成 I。"],
    variantGroup: "g4-review-yes-no-age-ten",
  }),
  candidate({
    id: "g4-review-yes-no-03",
    skill: "classroom_english",
    indicator: "能用 can 回答人物能力問句",
    microSkill: "yes-no-questions",
    difficulty: 1,
    purpose: "practice",
    prompt: "Bo knows how to fly a kite. Can Bo fly a kite?",
    correct: "Yes, he can.",
    distractors: ["No, he can't.", "Yes, he is.", "Yes, it can."],
    answerPosition: 3,
    explanation: "Bo 會放風箏，所以 Can Bo ...? 的肯定回答是 Yes, he can.",
    hints: ["問句使用 Can，簡答也要使用 can。"],
    variantGroup: "g4-review-yes-no-bo-kite",
  }),
  candidate({
    id: "g4-review-yes-no-04",
    skill: "classroom_english",
    indicator: "能依複數物品資訊做否定簡答",
    microSkill: "yes-no-questions",
    difficulty: 1,
    purpose: "practice",
    prompt: "The basket has bananas, not oranges. Are these oranges?",
    correct: "No, they aren't.",
    distractors: ["Yes, they are.", "No, it isn't.", "No, these don't."],
    answerPosition: 0,
    explanation: "籃子裡不是柳橙，要否定回答；these 是複數，所以使用 No, they aren't.",
    hints: ["先判斷 yes 或 no，再把 these 換成 they。"],
    variantGroup: "g4-review-yes-no-bananas",
  }),
  candidate({
    id: "g4-review-yes-no-05",
    skill: "classroom_english",
    indicator: "能依第一人稱擁有資訊回答 Do you ...?",
    microSkill: "yes-no-questions",
    difficulty: 2,
    purpose: "rescue",
    prompt: "A: I have a cat, but I don't have a dog. B: Do you have a dog? A: ___",
    correct: "No, I don't.",
    distractors: ["Yes, I do.", "No, I am not.", "No, it doesn't."],
    answerPosition: 1,
    explanation: "說話者明確表示沒有狗，因此 Do you ...? 要回答 No, I don't.",
    hints: ["找出 but 後面的資訊，再沿用問句中的 do。"],
    variantGroup: "g4-review-yes-no-have-dog",
  }),
  candidate({
    id: "g4-review-yes-no-06",
    skill: "classroom_english",
    indicator: "能從行程資訊回答 Does it ...?",
    microSkill: "yes-no-questions",
    difficulty: 2,
    purpose: "review",
    prompt: "The music club meets on Tuesday. Does it meet on Monday?",
    correct: "No, it doesn't.",
    distractors: ["Yes, it does.", "No, they don't.", "No, it isn't."],
    answerPosition: 2,
    explanation: "社團在星期二而不是星期一聚會，所以 Does it ...? 的否定簡答是 No, it doesn't.",
    hints: ["日期不相符，要選 no；Does 問句用 doesn't 回答。"],
    variantGroup: "g4-review-yes-no-music-club",
  }),
  candidate({
    id: "g4-review-yes-no-07",
    skill: "classroom_english",
    indicator: "能整合短文人物動作回答進行式問句",
    microSkill: "yes-no-questions",
    difficulty: 2,
    purpose: "boss",
    prompt: "Ivy is reading, and Ken is drawing in the classroom. Is Ken reading?",
    correct: "No, he isn't.",
    distractors: ["Yes, he is.", "No, he doesn't.", "No, she isn't."],
    answerPosition: 3,
    explanation: "reading 的人是 Ivy，Ken 正在 drawing，因此 Is Ken reading? 要回答 No, he isn't.",
    hints: ["先把兩個名字各自連到正確動作，再選 Ken 的回答。"],
    variantGroup: "g4-review-yes-no-ken-reading",
  }),

  candidate({
    id: "g4-review-cvc-01",
    skill: "phonics",
    indicator: "能從聽到的短母音辨認 CVC 字",
    microSkill: "cvc-decoding",
    difficulty: 1,
    purpose: "diagnostic",
    modality: "audio",
    audioTranscript: "cat",
    prompt: "Listen to the word. Which written word did you hear?",
    correct: "cat",
    distractors: ["cut", "cot", "cap"],
    answerPosition: 0,
    explanation: "音檔是 /k/ /æ/ /t/，依序對應 c-a-t，因此選 cat。",
    hints: ["先聽中間的短 a 音，再確認最後是 /t/。"],
    variantGroup: "g4-review-cvc-cat-listening",
  }),
  candidate({
    id: "g4-review-cvc-02",
    skill: "phonics",
    indicator: "能將三個音素合併成 CVC 字",
    microSkill: "cvc-decoding",
    difficulty: 1,
    purpose: "practice",
    prompt: "Blend the sounds /p/ /ɛ/ /n/. Which word do they make?",
    correct: "pen",
    distractors: ["pan", "pin", "pet"],
    answerPosition: 1,
    explanation: "/p/、短 e、/n/ 依序合音，拼成 p-e-n，也就是 pen。",
    hints: ["保留開頭 p 和結尾 n，專心分辨中間母音。"],
    variantGroup: "g4-review-cvc-pen-blend",
  }),
  candidate({
    id: "g4-review-cvc-03",
    skill: "phonics",
    indicator: "能依圖片意義選出正確 CVC 拼字",
    microSkill: "cvc-decoding",
    difficulty: 1,
    purpose: "practice",
    modality: "image",
    imageScene: "bright-sun-over-green-hill",
    imageAlt: "綠色小山上方有一個明亮物體的自然景色圖",
    prompt: "Which CVC word names the bright object in the sky?",
    correct: "sun",
    distractors: ["son", "sum", "sit"],
    answerPosition: 2,
    explanation: "圖片是太陽，英文拼作 s-u-n；son 雖同音，但意思是兒子。",
    hints: ["先想太陽的英文，再檢查中間 u 與結尾 n。"],
    variantGroup: "g4-review-cvc-sun-image",
  }),
  candidate({
    id: "g4-review-cvc-04",
    skill: "phonics",
    indicator: "能依字首音與韻尾辨認 CVC 字",
    microSkill: "cvc-decoding",
    difficulty: 1,
    purpose: "practice",
    prompt: "Which -og word begins with the sound /l/?",
    correct: "log",
    distractors: ["dog", "fog", "leg"],
    answerPosition: 3,
    explanation: "log 以 /l/ 開頭，並保留 -og 韻尾；dog、fog 的字首不同，leg 的韻尾不同。",
    hints: ["同時檢查第一個字母 l 和最後兩個字母 og。"],
    variantGroup: "g4-review-cvc-log-word-family",
  }),
  candidate({
    id: "g4-review-cvc-05",
    skill: "phonics",
    indicator: "能替換字首音形成新的 CVC 字",
    microSkill: "cvc-decoding",
    difficulty: 2,
    purpose: "rescue",
    prompt: "Change the first sound in cat from /k/ to /h/. Which new word do you make?",
    correct: "hat",
    distractors: ["hot", "ham", "cat"],
    answerPosition: 0,
    explanation: "cat 保留 -at，只把字首 /k/ 換成 /h/，便得到 h-a-t：hat。",
    hints: ["不要改中間 a 和結尾 t，只替換第一個音。"],
    variantGroup: "g4-review-cvc-cat-to-hat",
  }),
  candidate({
    id: "g4-review-cvc-06",
    skill: "phonics",
    indicator: "能替換中間短母音形成新的 CVC 字",
    microSkill: "cvc-decoding",
    difficulty: 2,
    purpose: "review",
    prompt: "Change the middle sound in pin from short i to short a. Which word do you make?",
    correct: "pan",
    distractors: ["pen", "pin", "pat"],
    answerPosition: 1,
    explanation: "pin 的 p 與 n 保持不變，把中間 i 換成 a，拼成 p-a-n：pan。",
    hints: ["新字仍以 p 開頭、n 結尾，只有母音改變。"],
    variantGroup: "g4-review-cvc-pin-to-pan",
  }),
  candidate({
    id: "g4-review-cvc-07",
    skill: "phonics",
    indicator: "能連續進行合音與字尾音替換",
    microSkill: "cvc-decoding",
    difficulty: 2,
    purpose: "boss",
    prompt: "Blend /r/ /ʌ/ /n/ to make run. Then replace the final /n/ with /g/. Which word is left?",
    correct: "rug",
    distractors: ["run", "rub", "rig"],
    answerPosition: 2,
    explanation: "run 的前兩個音 /r/ /ʌ/ 不變，將結尾 /n/ 換成 /g/ 後得到 r-u-g：rug。",
    hints: ["先拼出 run，再只改最後一個子音。"],
    variantGroup: "g4-review-cvc-run-to-rug",
  }),
];
