import { pilotQuestion, type PilotQuestionSeed } from "../pilot/pilot-factory";

const q = (seed: Omit<PilotQuestionSeed, "grade">) => pilotQuestion({ grade: 6, ...seed });

export const grade6ReviewCandidates = [
  q({
    id: "g6-review-place-01",
    skill: "comprehension",
    indicator: "能依活動目的判斷要前往的公共場所",
    microSkill: "place-and-destination",
    difficulty: 1,
    purpose: "diagnostic",
    prompt: "Nora wants to borrow an English storybook. Where is she going?",
    options: [
      "She is going to the library.",
      "She is walking to the swimming pool.",
      "She is visiting the flower shop.",
      "She is waiting at the police station.",
    ],
    answerIndex: 0,
    explanation: "borrow a storybook 表示要借故事書，因此目的地是 library（圖書館）。",
    hints: ["先圈出 borrow 和 storybook，再想哪個場所能借到書。"],
    variantGroup: "g6-place-library-book",
  }),
  q({
    id: "g6-review-place-02",
    skill: "vocabulary",
    indicator: "能依寄送物品的需求辨認場所名稱",
    microSkill: "place-and-destination",
    difficulty: 1,
    purpose: "practice",
    prompt: "Ethan needs to mail a birthday card to his cousin. Which place should he visit?",
    options: [
      "the post office beside the bank",
      "the night market near the river",
      "the playground behind the school",
      "the movie theater on King Street",
    ],
    answerIndex: 0,
    explanation: "mail a birthday card 是寄生日卡片，應前往 post office（郵局）。",
    hints: ["想一想：哪個場所提供寄信和寄卡片的服務？"],
    variantGroup: "g6-place-post-office-card",
  }),
  q({
    id: "g6-review-place-03",
    skill: "comprehension",
    indicator: "能從購物需求推論正確去向",
    microSkill: "place-and-destination",
    difficulty: 1,
    purpose: "rescue",
    prompt: "We need fresh bread for breakfast. Where are we going?",
    options: [
      "We are heading to the bakery.",
      "We are entering the science museum.",
      "We are driving toward the airport.",
      "We are crossing over to the stadium.",
    ],
    answerIndex: 0,
    explanation: "fresh bread 是新鮮麵包，最合理的去處是 bakery（麵包店）。",
    hints: ["把 fresh bread 當成關鍵商品，找出販售它的地方。"],
    variantGroup: "g6-place-bakery-breakfast",
  }),
  q({
    id: "g6-review-place-04",
    skill: "classroom_english",
    indicator: "能理解交通場站與搭乘目的",
    microSkill: "place-and-destination",
    difficulty: 1,
    purpose: "practice",
    prompt: "A: Where is Grandpa going? B: He wants to catch the 9:10 train to Tainan.",
    options: [
      "He is going to the train station.",
      "He is checking in at the city hotel.",
      "He is shopping inside the toy store.",
      "He is having lunch at the food court.",
    ],
    answerIndex: 0,
    explanation: "catch the train 是搭火車，所以 Grandpa 要去 train station（火車站）。",
    hints: ["注意交通工具 train，選擇可以搭乘它的場站。"],
    variantGroup: "g6-place-station-tainan",
  }),
  q({
    id: "g6-review-place-05",
    skill: "comprehension",
    indicator: "能整合對話中的展覽線索判斷目的地",
    microSkill: "place-and-destination",
    difficulty: 2,
    purpose: "review",
    prompt:
      "A: Why are Lily and Max taking the bus downtown? B: They want to see the new dinosaur exhibition. Where are they going?",
    options: [
      "They are going to the natural history museum.",
      "They are going to the neighborhood clinic.",
      "They are going to the sports center.",
      "They are going to the fruit market.",
    ],
    answerIndex: 0,
    explanation: "dinosaur exhibition 是恐龍展覽，通常在 natural history museum（自然史博物館）展出。",
    hints: ["先找出他們想看的東西，再配對最可能展示該物品的場所。"],
    variantGroup: "g6-place-museum-dinosaur",
  }),
  q({
    id: "g6-review-place-06",
    skill: "comprehension",
    indicator: "能依身體狀況與服務內容推論去向",
    microSkill: "place-and-destination",
    difficulty: 2,
    purpose: "practice",
    prompt:
      "Owen says, “My tooth hurts, and I have an appointment at three.” What is his destination?",
    options: [
      "the dental clinic across from the park",
      "the pet shop next to the bookstore",
      "the art classroom on the second floor",
      "the bus stop in front of the temple",
    ],
    answerIndex: 0,
    explanation: "tooth hurts 加上 appointment，表示 Owen 要到 dental clinic（牙科診所）看牙。",
    hints: ["把 tooth 與 appointment 兩條線索一起判斷，不要只看時間。"],
    variantGroup: "g6-place-dentist-appointment",
  }),
  q({
    id: "g6-review-place-07",
    skill: "comprehension",
    indicator: "能依行程先後判讀中途目的地",
    microSkill: "place-and-destination",
    difficulty: 3,
    purpose: "boss",
    prompt:
      "Jay's Saturday plan says: 9:00 return books; 10:00 send a package; 11:00 meet Dad in the park. Where will Jay be at 10:00?",
    options: [
      "At the parcel counter in the post office.",
      "At the return desk in the town library.",
      "At the duck pond in Green Park.",
      "At the ticket gate in Central Station.",
    ],
    answerIndex: 0,
    explanation: "行程表 10:00 的任務是 send a package，因此 Jay 當時會在郵局的包裹櫃檯。",
    hints: ["先鎖定 10:00 那一列，再把 send a package 對應到正確服務場所。"],
    variantGroup: "g6-place-itinerary-package",
  }),

  q({
    id: "g6-review-progressive-01",
    skill: "grammar",
    indicator: "能以現在進行式描述單數主詞的即時動作",
    microSkill: "present-progressive",
    difficulty: 1,
    purpose: "diagnostic",
    prompt:
      "Water is flowing from Mia's watering can onto the yellow flowers right now. What is she doing?",
    options: [
      "She is watering the yellow flowers.",
      "She waters the garden every Sunday.",
      "She watered the plants last night.",
      "She can draw a beautiful garden.",
    ],
    answerIndex: 0,
    explanation: "right now 表示動作正在發生，Mia 是單數，所以使用 She is watering。",
    hints: ["看到 right now，要找 be 動詞加上 V-ing 的句子。"],
    variantGroup: "g6-progressive-watering-flowers",
  }),
  q({
    id: "g6-review-progressive-02",
    skill: "grammar",
    indicator: "能以現在進行式描述複數主詞的即時動作",
    microSkill: "present-progressive",
    difficulty: 1,
    purpose: "practice",
    prompt: "Look! The boys ___ basketball on the playground.",
    options: ["are playing", "is playing", "are play", "playing"],
    answerIndex: 0,
    explanation: "The boys 是複數主詞，Look! 表示正在進行，因此填 are playing。",
    hints: ["先用複數主詞決定 are，再找動詞 play 的 -ing 形式。"],
    variantGroup: "g6-progressive-boys-basketball",
  }),
  q({
    id: "g6-review-progressive-03",
    skill: "grammar",
    indicator: "能理解現在進行式否定句的意義",
    microSkill: "present-progressive",
    difficulty: 1,
    purpose: "rescue",
    prompt: "Leo is studying for tomorrow's test. Which sentence is also true?",
    options: [
      "He is not sleeping on the sofa.",
      "He does not studies at his desk.",
      "He are not reading his notes.",
      "He not is preparing for school.",
    ],
    answerIndex: 0,
    explanation: "Leo 正在準備考試，所以「他沒有在沙發上睡覺」合理，且 is not sleeping 結構正確。",
    hints: ["現在進行式的否定要把 not 放在 is 後面。"],
    variantGroup: "g6-progressive-negative-studying",
  }),
  q({
    id: "g6-review-progressive-04",
    skill: "grammar",
    indicator: "能辨認短母音動詞的現在分詞拼法",
    microSkill: "present-progressive",
    difficulty: 1,
    purpose: "practice",
    prompt: "The dog is ___ after the red ball now. Choose the correct form of “run.”",
    options: [
      "running across the grass",
      "runing beside the fence",
      "runs around the tree",
      "ran through the gate",
    ],
    answerIndex: 0,
    explanation: "run 變成現在分詞時要重複字尾 n 再加 -ing，拼成 running。",
    hints: ["run 是短母音加單一子音結尾，字尾子音要再寫一次。"],
    variantGroup: "g6-progressive-running-spelling",
  }),
  q({
    id: "g6-review-progressive-05",
    skill: "comprehension",
    indicator: "能從電話對話辨識兩人正在進行的不同動作",
    microSkill: "present-progressive",
    difficulty: 2,
    purpose: "review",
    prompt:
      "Amy: Is your family busy? Ben: Yes. Mom is making soup, and Dad is setting the table. What are Ben's parents doing?",
    options: [
      "His mother is cooking, and his father is preparing the table.",
      "His mother is shopping, and his father is washing the car.",
      "His parents are ordering dinner from a restaurant.",
      "His parents are resting together in the living room.",
    ],
    answerIndex: 0,
    explanation: "making soup 是煮湯，setting the table 是擺餐具；第一個選項完整保留兩個動作。",
    hints: ["將 Mom 與 Dad 的動作分開做記號，再找同時符合兩人的選項。"],
    variantGroup: "g6-progressive-parents-dinner",
  }),
  q({
    id: "g6-review-progressive-06",
    skill: "grammar",
    indicator: "能選出主詞與現在進行式一致的完整句",
    microSkill: "present-progressive",
    difficulty: 2,
    purpose: "practice",
    prompt: "Which sentence correctly describes an action happening at this moment?",
    options: [
      "Our English teacher is writing a sentence on the board.",
      "My classmates is open their workbooks now.",
      "I are listening to a new dialogue today.",
      "The student answering the question at present.",
    ],
    answerIndex: 0,
    explanation: "單數主詞 Our English teacher 搭配 is writing，句型與時間語意都正確。",
    hints: ["逐一檢查每個主詞後面的 be 動詞，再確認主要動詞有 -ing。"],
    variantGroup: "g6-progressive-classroom-agreement",
  }),
  q({
    id: "g6-review-progressive-07",
    skill: "comprehension",
    indicator: "能整合短文中的人物與即時動作",
    microSkill: "present-progressive",
    difficulty: 2,
    purpose: "boss",
    prompt:
      "It is 7:30. Zoe is packing her schoolbag. Her brother is feeding the cat, and their parents are washing the dishes. Who is taking care of the pet?",
    options: [
      "Zoe's brother is feeding the cat.",
      "Zoe is putting notebooks into her bag.",
      "Their mother is rinsing the dinner plates.",
      "Their father is cleaning the kitchen cups.",
    ],
    answerIndex: 0,
    explanation: "taking care of the pet 對應 feeding the cat，短文明確說這是 Zoe 的弟弟正在做的事。",
    hints: ["先把 pet 對應到 cat，再回短文找 cat 前面的人物。"],
    variantGroup: "g6-progressive-family-evening",
  }),

  q({
    id: "g6-review-clothing-01",
    skill: "grammar",
    indicator: "能正確使用 have 描述自己的衣物",
    microSkill: "clothing-and-have",
    difficulty: 1,
    purpose: "diagnostic",
    prompt: "I ___ in my sports bag for today's baseball game.",
    options: ["have a red cap", "has a red cap", "am a red cap", "wears a red cap"],
    answerIndex: 0,
    explanation: "主詞 I 要搭配 have，因此完整意思是「我有一頂今天球賽要戴的紅帽」。",
    hints: ["I、you、we、they 表示「有」時，都使用 have。"],
    variantGroup: "g6-clothing-have-cap",
  }),
  q({
    id: "g6-review-clothing-02",
    skill: "grammar",
    indicator: "能正確使用 has 描述第三人稱單數的衣物",
    microSkill: "clothing-and-have",
    difficulty: 1,
    purpose: "practice",
    prompt: "Tina ___ for school events.",
    options: [
      "has two skirts: a green one and a purple one",
      "have two skirts: a green one and a purple one",
      "am carrying two skirts: a green one and a purple one",
      "are two skirts: a green one and a purple one",
    ],
    answerIndex: 0,
    explanation: "Tina 是第三人稱單數，要用 has 表示她有兩件裙子。",
    hints: ["把 Tina 暫時換成 she，就能判斷應使用 has。"],
    variantGroup: "g6-clothing-has-skirts",
  }),
  q({
    id: "g6-review-clothing-03",
    skill: "vocabulary",
    indicator: "能依天氣需求選擇合適衣物",
    microSkill: "clothing-and-have",
    difficulty: 1,
    purpose: "rescue",
    prompt: "It is raining hard. Which item should Kevin have before he leaves home?",
    options: [
      "a waterproof yellow raincoat",
      "a wool hat for snowy weather",
      "a swimsuit with orange stripes",
      "a pair of indoor bedroom slippers",
    ],
    answerIndex: 0,
    explanation: "raining hard 表示下大雨，waterproof raincoat 是最符合情境的防雨衣物。",
    hints: ["找出能讓身體在大雨中保持乾燥的衣物。"],
    variantGroup: "g6-clothing-raincoat-weather",
  }),
  q({
    id: "g6-review-clothing-04",
    skill: "comprehension",
    indicator: "能依人物擁有的衣物辨識物品",
    microSkill: "clothing-and-have",
    difficulty: 1,
    purpose: "practice",
    prompt: "Ken has a blue T-shirt with a white star. Which shirt belongs to Ken?",
    options: [
      "The blue shirt with one white star.",
      "The black shirt with two red hearts.",
      "The white shirt with three green trees.",
      "The gray shirt with four yellow moons.",
    ],
    answerIndex: 0,
    explanation: "題幹同時指定 blue、T-shirt 與 a white star，只有第一個選項三項都符合。",
    hints: ["依序核對顏色、衣物種類、圖案三個特徵。"],
    variantGroup: "g6-clothing-shirt-star",
  }),
  q({
    id: "g6-review-clothing-05",
    skill: "comprehension",
    indicator: "能依低溫情境判斷需準備的衣物組合",
    microSkill: "clothing-and-have",
    difficulty: 2,
    purpose: "review",
    prompt:
      "The class will visit a mountain tomorrow. The weather report says 8°C and strong wind. What should Ruby have in her backpack?",
    options: [
      "a thick coat and a warm scarf",
      "a beach towel and a sun visor",
      "a dance costume and silver gloves",
      "a school uniform and a name tag",
    ],
    answerIndex: 0,
    explanation: "8°C 加上 strong wind 代表寒冷多風，thick coat 與 warm scarf 能提供保暖。",
    hints: ["先把 8°C 判斷為冷，再找能保護身體與頸部的組合。"],
    variantGroup: "g6-clothing-mountain-cold",
  }),
  q({
    id: "g6-review-clothing-06",
    skill: "grammar",
    indicator: "能依不同主詞選用 have 與 has",
    microSkill: "clothing-and-have",
    difficulty: 2,
    purpose: "practice",
    prompt: "Choose the sentence with the correct use of have or has.",
    options: [
      "My twin brothers have matching green jackets.",
      "Ella have a belt with a round buckle.",
      "The baby shoes has soft white laces.",
      "Our grandfather have a brown vest.",
    ],
    answerIndex: 0,
    explanation: "My twin brothers 是複數主詞，需搭配 have；其他單數主詞應使用 has。",
    hints: ["先將四個主詞分成單數與複數，再檢查動詞形式。"],
    variantGroup: "g6-clothing-have-has-agreement",
  }),
  q({
    id: "g6-review-clothing-07",
    skill: "comprehension",
    indicator: "能整合失物特徵與人物陳述找出物主",
    microSkill: "clothing-and-have",
    difficulty: 2,
    purpose: "boss",
    prompt:
      "A glove is in the lost-and-found box. It is small, pink, and has a rabbit on it. Who is most likely its owner?",
    options: [
      "May, who has small pink gloves with rabbit pictures",
      "Noah, who has large navy gloves with boat pictures",
      "Ivy, who has short purple socks with cat pictures",
      "Sam, who has a long red scarf with bear pictures",
    ],
    answerIndex: 0,
    explanation: "失物的尺寸、顏色、種類與兔子圖案都和 May 的手套描述完全相同。",
    hints: ["用 small、pink、glove、rabbit 四個條件逐項排除不合者。"],
    variantGroup: "g6-clothing-lost-glove",
  }),

  q({
    id: "g6-review-occupation-01",
    skill: "vocabulary",
    indicator: "能由工作內容辨認餐飲職業",
    microSkill: "occupation-and-family",
    difficulty: 1,
    purpose: "diagnostic",
    prompt: "My father cooks meals in a busy restaurant. What is his job?",
    options: [
      "He is the restaurant's chef.",
      "He is a violin player in an orchestra.",
      "He is a mail carrier for our street.",
      "He is a mechanic at a repair shop.",
    ],
    answerIndex: 0,
    explanation: "在 restaurant 裡負責 cooks meals 的人是 chef（廚師）。",
    hints: ["把工作動作 cooks meals 與工作地點 restaurant 配在一起。"],
    variantGroup: "g6-occupation-father-chef",
  }),
  q({
    id: "g6-review-occupation-02",
    skill: "vocabulary",
    indicator: "能由工作場所與任務辨認教育職業",
    microSkill: "occupation-and-family",
    difficulty: 1,
    purpose: "practice",
    prompt: "Aunt Grace teaches math at an elementary school. What does she do?",
    options: [
      "She works there as a math teacher.",
      "She paints houses as a decorator.",
      "She grows rice as a local farmer.",
      "She delivers news as a TV reporter.",
    ],
    answerIndex: 0,
    explanation: "teaches math at an elementary school 清楚指出 Aunt Grace 是數學老師。",
    hints: ["看到 teaches 與 school，聯想在學校教導學生的職業。"],
    variantGroup: "g6-occupation-aunt-teacher",
  }),
  q({
    id: "g6-review-occupation-03",
    skill: "vocabulary",
    indicator: "能由緊急任務辨認公共安全職業",
    microSkill: "occupation-and-family",
    difficulty: 1,
    purpose: "rescue",
    prompt: "Uncle Ray drives a red truck and puts out fires. Which job does he have?",
    options: [
      "He has a job as a firefighter.",
      "He has a job as a tour guide.",
      "He has a job as a photographer.",
      "He has a job as a fisherman.",
    ],
    answerIndex: 0,
    explanation: "drives a red truck 與 puts out fires 都是 firefighter（消防員）的典型工作線索。",
    hints: ["哪一種工作會開消防車並把火撲滅？"],
    variantGroup: "g6-occupation-uncle-firefighter",
  }),
  q({
    id: "g6-review-occupation-04",
    skill: "comprehension",
    indicator: "能理解核心家庭成員的親屬關係",
    microSkill: "occupation-and-family",
    difficulty: 1,
    purpose: "practice",
    prompt: "Emma and I have the same parents. Emma is a girl. Who is Emma to me?",
    options: [
      "Emma is my sister.",
      "Emma is my grandmother.",
      "Emma is my daughter.",
      "Emma is my niece.",
    ],
    answerIndex: 0,
    explanation: "兩人 have the same parents 表示是手足，Emma 是女孩，因此她是 sister（姊妹）。",
    hints: ["先判斷 same parents 代表哪一種同輩親屬，再看 Emma 的性別。"],
    variantGroup: "g6-family-same-parents-sister",
  }),
  q({
    id: "g6-review-occupation-05",
    skill: "comprehension",
    indicator: "能由兩層家庭關係推論稱謂",
    microSkill: "occupation-and-family",
    difficulty: 2,
    purpose: "review",
    prompt: "Ms. Lin is my father's sister. What should I call Ms. Lin?",
    options: [
      "She is my aunt.",
      "She is my cousin.",
      "She is my mother-in-law.",
      "She is my granddaughter.",
    ],
    answerIndex: 0,
    explanation: "father's sister 是爸爸的姊妹，對我而言稱為 aunt（姑姑）。",
    hints: ["從 my father 出發，往他的 sister 走一層家庭關係。"],
    variantGroup: "g6-family-fathers-sister",
  }),
  q({
    id: "g6-review-occupation-06",
    skill: "comprehension",
    indicator: "能整合家庭成員、職業與工作地點",
    microSkill: "occupation-and-family",
    difficulty: 2,
    purpose: "practice",
    prompt:
      "Liam's mother flies airplanes. His father takes care of patients in a hospital. Which statement is correct?",
    options: [
      "Liam's mother is a pilot, and his father works with patients.",
      "Liam's mother is a dentist in a clinic.",
      "Both parents work as school librarians.",
      "Neither parent helps other people at work.",
    ],
    answerIndex: 0,
    explanation: "flies airplanes 表示母親是 pilot；父親在醫院照顧病人，正解只陳述題幹能確定的資訊。",
    hints: ["分別核對 mother 與 father 的工作內容，不替題幹補上未說明的職稱。"],
    variantGroup: "g6-occupation-parents-pilot-nurse",
  }),
  q({
    id: "g6-review-occupation-07",
    skill: "comprehension",
    indicator: "能依多人物職業線索完成親屬配對",
    microSkill: "occupation-and-family",
    difficulty: 3,
    purpose: "boss",
    prompt:
      "Three relatives have different jobs. Mia's aunt designs buildings. Her uncle fixes teeth. Her cousin works with animals. Who is the architect?",
    options: [
      "Mia's aunt, who designs buildings",
      "Mia's uncle, who treats sore teeth",
      "Mia's cousin, who cares for sick pets",
      "Mia's neighbor, who repairs bicycles",
    ],
    answerIndex: 0,
    explanation: "architect 的工作是設計建築物；題幹說 designs buildings 的人是 Mia's aunt。",
    hints: ["先回想 architect 的工作內容，再回題幹找做這件事的親屬。"],
    variantGroup: "g6-occupation-relatives-logic",
  }),

  q({
    id: "g6-review-integrated-01",
    skill: "comprehension",
    indicator: "能從點餐對話找出顧客選擇",
    microSkill: "integrated-dialogue-text",
    difficulty: 1,
    purpose: "diagnostic",
    prompt:
      "Server: Would you like noodles or rice? Hana: Rice, please, and a glass of milk. What does Hana order?",
    options: [
      "A bowl of rice and one glass of milk.",
      "A plate of noodles and one cup of tea.",
      "A cheese sandwich and one bottle of juice.",
      "A vegetable salad and one bowl of soup.",
    ],
    answerIndex: 0,
    explanation: "Hana 直接回答 Rice, please，並補充 a glass of milk，所以餐點是飯和牛奶。",
    hints: ["把食物與飲料分成兩格，逐一記下 Hana 親口說的選擇。"],
    variantGroup: "g6-integrated-order-rice-milk",
  }),
  q({
    id: "g6-review-integrated-02",
    skill: "comprehension",
    indicator: "能從課後行程讀出時間與活動",
    microSkill: "integrated-dialogue-text",
    difficulty: 1,
    purpose: "practice",
    prompt:
      "Ben's after-school plan: 3:30 homework club; 4:30 soccer practice; 6:00 dinner. What is Ben doing at 4:30?",
    options: [
      "He is practicing soccer with his team.",
      "He is finishing homework in the study room.",
      "He is eating dinner with his grandparents.",
      "He is riding the morning bus to school.",
    ],
    answerIndex: 0,
    explanation: "行程表的 4:30 對應 soccer practice，因此 Ben 正在和球隊練足球。",
    hints: ["只讀 4:30 那一列，別被前後兩個時間的活動干擾。"],
    variantGroup: "g6-integrated-schedule-soccer",
  }),
  q({
    id: "g6-review-integrated-03",
    skill: "comprehension",
    indicator: "能從留言辨識人物所在位置",
    microSkill: "integrated-dialogue-text",
    difficulty: 1,
    purpose: "rescue",
    prompt:
      "Note from Ava: “I'm at the library doing our science project. Please meet me by the front desk at five.” Where is Ava now?",
    options: [
      "She is inside the library.",
      "She is outside the science laboratory.",
      "She is beside the school playground.",
      "She is near the supermarket entrance.",
    ],
    answerIndex: 0,
    explanation: "留言開頭明確寫 I'm at the library，所以 Ava 現在人在圖書館內。",
    hints: ["位置題先找 at 後面的地點，不必先處理見面時間。"],
    variantGroup: "g6-integrated-note-library",
  }),
  q({
    id: "g6-review-integrated-04",
    skill: "comprehension",
    indicator: "能整合天氣與對話判斷攜帶衣物的原因",
    microSkill: "integrated-dialogue-text",
    difficulty: 1,
    purpose: "practice",
    prompt:
      "Kai: It's warm now. Why do you have a jacket? June: The weather report says it will be cold tonight. Why does June have a jacket?",
    options: [
      "She expects the temperature to drop tonight.",
      "She plans to give the jacket to Kai now.",
      "She needs the pockets to carry warm food.",
      "She wants to wear the jacket while swimming.",
    ],
    answerIndex: 0,
    explanation: "June 說 tonight 會變冷，所以先帶外套是為了晚上的降溫做準備。",
    hints: ["比較 warm now 與 cold tonight，注意時間改變帶來的天氣差異。"],
    variantGroup: "g6-integrated-weather-jacket",
  }),
  q({
    id: "g6-review-integrated-05",
    skill: "comprehension",
    indicator: "能理解公共告示中的規則與時間",
    microSkill: "integrated-dialogue-text",
    difficulty: 1,
    purpose: "practice",
    prompt:
      "Pool notice: “Open 9:00–17:00. Wear a swim cap. No food beside the pool.” What may a visitor do?",
    options: [
      "Swim at ten o'clock while wearing a cap.",
      "Eat a hamburger beside the shallow pool.",
      "Enter the building at seven in the evening.",
      "Leave the swim cap inside a locker all day.",
    ],
    answerIndex: 0,
    explanation: "10:00 在開放時間內，且 visitor 戴泳帽，完全符合告示的時間與服裝規定。",
    hints: ["同時檢查 open hours、swim cap、no food 三條規則。"],
    variantGroup: "g6-integrated-pool-notice",
  }),
  q({
    id: "g6-review-integrated-06",
    skill: "comprehension",
    indicator: "能由對話中的需求與路線推論下一個地點",
    microSkill: "integrated-dialogue-text",
    difficulty: 2,
    purpose: "review",
    prompt:
      "Rita: I finished buying fruit. Now I need medicine for Grandma. Tom: The drugstore is across from the bank. Where will Rita go next?",
    options: [
      "She will go to the drugstore for the medicine.",
      "She will return to the fruit stand for apples.",
      "She will wait inside the bank for Grandma.",
      "She will walk home without the medicine.",
    ],
    answerIndex: 0,
    explanation: "Rita 下一個需求是 medicine，Tom 又提供 drugstore 的位置，因此她接著會去藥局。",
    hints: ["先找 Rita 還沒完成的任務，再選能確定完成該任務的地方。"],
    variantGroup: "g6-integrated-errand-drugstore",
  }),
  q({
    id: "g6-review-integrated-07",
    skill: "comprehension",
    indicator: "能整合原定行程與即時訊息判斷下一步",
    microSkill: "integrated-dialogue-text",
    difficulty: 2,
    purpose: "boss",
    prompt:
      "Leo planned to meet Sue at the park at 3:00. At 2:50 Sue texts, “It is raining. Let's meet inside the café next to the park.” What should Leo do?",
    options: [
      "Go to the café beside the park for the meeting.",
      "Stand by the park fountain in the heavy rain.",
      "Meet Sue at the train station at half past three.",
      "Cancel the meeting without reading Sue's message.",
    ],
    answerIndex: 0,
    explanation: "最新訊息因下雨把見面地點改到 park 旁的 café，Leo 應依更新後的安排前往。",
    hints: ["行程改動題要以時間較新的訊息為準，找出被更改的地點。"],
    variantGroup: "g6-integrated-rain-plan-change",
  }),
];
